<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100906
 * Desc:		This is the view of PKW details
 *********************************************************************************/
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$lang = $this -> lang;
$bike = $this -> bike;
$bikeCat = $this -> bikeCat;
$bookmark = $this -> bookmark;
$p = $this -> p;
$system = $this -> system;
$og = array('TITLE'=> ''
			, 'TYPE' => 'website'
			, 'IMAGE' => ''
			, 'URL' => ''
			, 'SITE_NAME' => ''
			, 'SITE_DESC' => array());
			
$str2NumFilter = new FormatSt2Num();
$strIsEmptyFilter = new FilterIsEmptyString();

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/bike_detail.css" />');
				
$tmpl -> readTmplFile('CONTENT', 'default/bike/detail.html');

//Set BIKE_BRAND BIKE_MODEL
$tmpl -> setValue('BIKE_BRAND_VAL', $bike['bikeBrandName']);
array_push($og['SITE_DESC'], $bike['bikeBrandName']);
$bikeModel = '';
if (isset($bike['bikeModelName']) && ($bike['bikeModelName'] != null)){
	$bikeModel = $bike['bikeModelName'];
	$og['SITE_DESC'][0] .= ' '.$bike['bikeModelName'];
}

//Set BIKE_MODEL_VAR_VAL
if (isset($bike['bikeModelVar']) && ($bike['bikeModelVar'] != null)){
	if ($bikeModel != ''){
		$bikeModel .= ' ';	
	}
	$bikeModel .= $bike['bikeModelVar'];	
}

$tmpl -> setValue('BIKE_MODEL_VAL', $bikeModel);

//Set BIKE_PRICE
$bikePriceVal = '<table>';

if(isset($bike['mwst']) && ($bike['mwst'] == '1') && isset($bike['mwstSatz']) && in_array($bike['mwstSatz'],$lang['V_MWST'])){
	$bikePriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $bike['bikePrice']*($bike['mwstSatz']/100+1),
												'dec_place' => 0
												)
										). '{-BIKE_PRICE_CURR-} ('.$lang['TXT_273'].')</td></tr>
					<tr><td>'.$str2NumFilter -> filter(array('val' => $bike['bikePrice'],
												'dec_place' => 0
												)
										).'{-BIKE_PRICE_CURR-} ('.$lang['TXT_274'].')</td></tr>
					<tr><td>'.$bike['mwstSatz'].'% '.$lang['TXT_270'].'</td></tr>';
}
elseif(isset($bike['mwst']) && ($bike['mwst'] == '1')){
	$bikePriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $bike['bikePrice'],
												'dec_place' => 0
												)
										).'{-BIKE_PRICE_CURR-}</td></tr>
					<tr><td>'.$lang['TXT_270'].'</td></tr>';
}else{
	$bikePriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $bike['bikePrice'],
												'dec_place' => 0
												)
										).'{-BIKE_PRICE_CURR-}</td></tr>
					<tr><td>'.$lang['TXT_275'].'</td></tr>';
}
$bikePriceVal .= '</table>';
$tmpl -> setValue('BIKE_PRICE_VAL', $bikePriceVal);

$bikePriceCurr = '';
if (isset($lang['TXT_74'][$this->bike['bikePriceCurr']])){
	$bikePriceCurr = $lang['TXT_74'][$this->bike['bikePriceCurr']];
}
$tmpl -> setValue('BIKE_PRICE_CURR', $bikePriceCurr);


$bikePriceType = '';
if (isset($bike['bikePriceType']) && isset($lang['TXT_70'][$bike['bikePriceType']])){
	$bikePriceType = ', '.$lang['TXT_70'][$bike['bikePriceType']];
}
$tmpl -> setValue('BIKE_PRICE_TYPE_VAL', $bikePriceType);

//Set BIKE_KM
$bikeKMVal = $str2NumFilter -> filter($bike['bikeKM']);
if (isset($lang['TXT_75'][$bike['bikeKMType']])){
	$bikeKMVal .= ' '.$lang['TXT_75'][$bike['bikeKMType']];
}
$tmpl -> setValue('BIKE_KM_VAL', $bikeKMVal);
array_push($og['SITE_DESC'], $lang['TXT_14'].': '.$bikeKMVal);

//Set BIKE_POWER
$bikePower = '';
//KW?
if ($bike['bikePowerType'] == 0){
	$bikePower = $str2NumFilter -> filter(array('val' => $bike['bikePower'],
												'dec_place' => 0
												)
										).$lang['TXT_72'][0].' ('.
				$str2NumFilter -> filter(array('val' => ($bike['bikePower']*90/66),
												'dec_place' => 0
												)
										).$lang['TXT_72'][1].')';
}
//PS?
else if($bike['bikePowerType'] == 1){
	$bikePower = $str2NumFilter -> filter(array('val' => ($bike['bikePower'] * 66/90),
												'dec_place' => 0
												)
										).$lang['TXT_72'][0].' ('.
				$str2NumFilter -> filter(array('val' => $bike['bikePower'],
												'dec_place' => 0
												)
										).$lang['TXT_72'][1].')';	
}
if($bikePower == ""){
	$bikePower = "---";
}
$tmpl -> setValue('BIKE_POWER_VAL', $bikePower);
array_push($og['SITE_DESC'], $lang['TXT_10'].': '.$bikePower);

//Set BIKE_EZ
if($bike['bikeEZY'] == 9999){
	$tmpl -> setValue('BIKE_EZ', $lang['V_STATE'][0]);
	array_push($og['SITE_DESC'], $lang['TXT_7'].': '.$lang['V_STATE'][0]);
}
elseif (($bike['bikeEZM'] > 0) && ($bike['bikeEZY'] > 0)){
	$tmpl -> setValue('BIKE_EZ', $bike['bikeEZM'].'/'.$bike['bikeEZY']);
	array_push($og['SITE_DESC'], $lang['TXT_7'].': '.$bike['bikeEZM'].'/'.$bike['bikeEZY']);
}else{
	$tmpl -> setValue('BIKE_EZ', '');
}



//Set BIKE_OPTIONAL_SPEC
$bikeOpt = '';
//Add bikeCat
if (isset($bike['bikeCat']) && ($bike['bikeCat'] != -1) && is_array($bikeCat)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	foreach ($bikeCat as $key => $kVal){
		if (($kVal['bikeCatID'] == $bike['bikeCat']) && isset($lang['V_CAT'][$kVal['vcatID']])){		
			$bikeOpt .= '<li><span>'.$lang['TXT_18'].'</span>&nbsp;'.$lang['V_CAT'][$kVal['vcatID']].'</li>';
		}
	}
}
/*
$bikeCatVal = '';	
if (isset($this -> bike['bikeCat']) && is_array($bikeCat)){
	foreach($bikeCat as $key => $kVal){
		if (($kVal['bikeCatID'] == $this -> bike['bikeCat']) && isset($lang['V_CAT'][$kVal['vcatID']])){
			$bikeCatVal .= $lang['V_CAT'][$kVal['vcatID']];
			break;
		}
	}
}
$tmpl -> setValue('BIKE_CAT_VAL', $bikeCatVal);
*/

//Add bikeFuel
if (isset($lang['V_FUEL'][$bike['bikeFuel']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_15'].'</span>&nbsp;'.$lang['V_FUEL'][$bike['bikeFuel']].'</li>';
}
//Add bikeClr
if (isset($lang['V_CLR'][$bike['bikeClr']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	$bikeOpt .= '<li><span>'.$lang['TXT_19'].'</span>&nbsp;'.$lang['V_CLR'][$bike['bikeClr']];
	if (isset($bike['bikeClrMet'])){
		$bikeOpt .= ' '.$lang['TXT_20'];
	}
	$bikeOpt .= '</li>';
}
//Add bikeTUV
if (isset($bike['bikeTUVY']) && ($bike['bikeTUVY'] > 0)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_76'].'</span>';
	if (isset($bike['bikeTUVM']) && ($bike['bikeTUVM'] > 0)){
		$bikeOpt .= $bike['bikeTUVM'].'/';
	}
	$bikeOpt .= $bike['bikeTUVY'].'</li>';
}
//Add bikeAUV
if (isset($bike['bikeAUY']) && ($bike['bikeAUY'] > 0)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_77'].'</span>';
	if (isset($bike['bikeAUM']) && ($bike['bikeAUM'] > 0)){
		$bikeOpt .= $bike['bikeAUM'].'/';
	}
	$bikeOpt .= $bike['bikeAUY'].'</li>';
}
//Add bikeEcologicTag
if (isset($lang['V_ECOLOGIC_TAG'][$bike['bikeEcologicTag']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_85'].'</span>&nbsp;'.$lang['V_ECOLOGIC_TAG'][$bike['bikeEcologicTag']].'</li>';
}
//Add bikeEmissionNorm
if (isset($lang['V_EMISSION_NORM'][$bike['bikeEmissionNorm']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_22'].'</span>&nbsp;'.$lang['V_EMISSION_NORM'][$bike['bikeEmissionNorm']].'</li>';
}
//Add bikeCO2
if (isset($bike['bikeCO2']) && ($bike['bikeCO2'] != null)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_65'].'</span>&nbsp;'. $str2NumFilter -> filter(array(	'val' => $bike['bikeCO2'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_66'].'</li>';
}
//Add bikeUseIn
if (isset($bike['bikeUseIn']) && ($bike['bikeUseIn'] != null)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_62'].'</span>&nbsp;'. $str2NumFilter -> filter(array(	'val' => $bike['bikeUseIn'],
																			'dec_place' => 1
																		)
																).'&nbsp;'.$lang['TXT_64'].'</li>';
}
//Add bikeUseOut
if (isset($bike['bikeUseOut']) && ($bike['bikeUseOut'] != null)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_63'].'</span>&nbsp;'. $str2NumFilter -> filter(array(	'val' => $bike['bikeUseOut'],
																			'dec_place' => 1
																		)
																).'&nbsp;'.$lang['TXT_64'].'</li>';
}
//Add bikeCub
if (isset($bike['bikeCub']) && ($bike['bikeCub'] > 0)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_59'].'</span>&nbsp;'. $str2NumFilter -> filter(array(	'val' => $bike['bikeCub'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_60'].'</li>';
}
//Add bikeShift
if (isset($lang['V_SHIFT'][$bike['bikeShift']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt.= '<li><span>'.$lang['TXT_21'].'</span>&nbsp;'.$lang['V_SHIFT'][$bike['bikeShift']].'</li>';
}
//Add bikeWeight
if (isset($bike['bikeWeight']) && ($bike['bikeWeight'] > 0)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_57'].'</span>&nbsp;'.$str2NumFilter -> filter(array(	'val' => $bike['bikeWeight'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_67'].'</li>';
}
//Add bikeCyl
if (isset($bike['bikeCyl']) && ($bike['bikeCyl'] > 0)){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_58'].'</span>&nbsp;'. $str2NumFilter -> filter(array(	'val' => $bike['bikeCyl'],
																			'dec_place' => 0
																		)
																).'</li>';
}

//Add bikeState
if (isset($lang['V_STATE'][$bike['bikeState']])){
	if ($bikeOpt == ''){
		$bikeOpt = '<ul id="oth_detail">';
	}
	
	$bikeOpt .= '<li><span>'.$lang['TXT_17'].'</span>&nbsp;'.$lang['V_STATE'][$bike['bikeState']].'</li>';
}

if ($bikeOpt != null){
	$bikeOpt = '<label for="oth_detail"><strong>'.$lang['TXT_84'].'</strong></label>
				'.$bikeOpt.'
				</ul>';
}

$tmpl -> setValue('BIKE_OPTIONAL_SPEC', $bikeOpt);

//Add bikeDesc
$bikeDesc = '';
if (isset($bike['bikeDesc']) && ($strIsEmptyFilter -> filter($bike['bikeDesc']) == false)){
	$bikeDesc = '<label for="bikeDesc"><strong>'.$lang['TXT_68'].'</strong></label>
				<div id="bikeDesc" class="justify">'.nl2br($bike['bikeDesc']).'</div>';
}
$tmpl -> setValue('BIKE_DESC', $bikeDesc);

//Add bikeExt
$bikeExtStr = '';
if (isset($bike['bikeExt']) && is_array($bike['bikeExt']) && (count($bike['bikeExt'])>0)){
	//$bikeExtStr .= '<li>'.$lang['TXT_83'].'<br/>';
	$bikeExtStr = '<label for="bikeExtra"><strong>'.$lang['TXT_83'].'</strong></label>
				<div id="bikeExtra" class="justify">';
	foreach ($bike['bikeExt'] as $bikeExt){
		if (isset($lang['V_EXTRA'][$bikeExt['vextID']])){
			$bikeExtStr .= $lang['V_EXTRA'][$bikeExt['vextID']].', ';
		}
	}
	$bikeExtStr .= '</div><br/>';
}
$tmpl -> setValue('BIKE_EXTRA', $bikeExtStr);

//Set USER_ADS
$userAds = '';
if (isset($bike['userAds'])){
	switch ($bike['userAds']){
		case 1: $userAds = '&nbsp;('.$lang['TXT_33'][1].')';
				break;
		case 2: $userAds = '&nbsp;('.$lang['TXT_33'][2].')';
				break;
	}
}
$tmpl -> setValue('USER_ADS', $userAds);

//Set userFirm
$userFirm = '';
if (isset($bike['userFirm']) && ($bike['userFirm'] != null)){
	//$userFirm .= '<li><span>'.$lang['TXT_53'].'</span>'.$bike['userFirm'].'</li>';
	$userFirm .= '<li>'.$bike['userFirm'].'</li>';
}
$tmpl -> setValue('USER_FIRM', $userFirm);

//Set userName
//$userName = '<span>'.$lang['TXT_88'].'</span>'.$bike['userNName'].' '.$bike['userVName'];
$userName = $bike['userNName'].' '.$bike['userVName'];
$tmpl -> setValue('USER_NAME', $userName);

//Set userAdress
$userAddress = '';
if (isset($bike['userAdress']) || isset($bike['userPLZ']) || isset($bike['userOrt'])){
	if (isset($bike['userAdress']) && ($strIsEmptyFilter -> filter($bike['userAdress']) == false)){
		$userAddress .= '<li>'.$bike['userAdress'].'</li>';
	}
	if (isset($bike['userPLZ']) && isset($bike['userOrt'])
		 && ($strIsEmptyFilter -> filter($bike['userPLZ']) == false)
		  && ($strIsEmptyFilter -> filter($bike['userOrt']) == false)){
		$userAddress .= '<li>'.$bike['userPLZ'].' '.$bike['userOrt'].'</li>';
	}
	else if (isset($bike['userPLZ']) && ($strIsEmptyFilter -> filter($bike['userPLZ']) == false)){
		$userAddress .= '<li>'.$bike['userPLZ'].'</li>';
	}
	else if (isset($bike['userOrt']) && ($strIsEmptyFilter -> filter($bike['userOrt']) == false)){
		$userAddress .= '<li>'.$bike['userOrt'].'</li>';
	}
}
if ($userAddress != ''){
	//$userAddress = '	<li><span>'.$lang['TXT_54'].'</span><ul>'.$userAddress.'</ul></li>';
	$userAddress = '	<li><ul>'.$userAddress.'</ul></li>';
}
else{
	$userAddress = '';
}
$tmpl -> setValue('USER_ADDRESS', $userAddress);

//bikeLoc
$bikeLoc = '';
$bikeLocCountry = 'DE';
$bikeLocPLZOrt = '';
if (isset($bike['bikeLocPLZ']) && ($bike['bikeLocPLZ'] != null)){
	if ($bikeLoc != ''){
		$bikeLoc .= ' ';
	}
	$bikeLoc .= $bike['bikeLocPLZ'];
	$bikeLocPLZOrt .= $bike['bikeLocPLZ'];
}
if (isset($bike['bikeLocOrt']) && ($bike['bikeLocOrt'] != null)){
	if ($bikeLoc != ''){
		$bikeLoc .= ' ';
	}
	$bikeLoc .= ' '.$bike['bikeLocOrt'];
	
	if ($bikeLocPLZOrt != ''){
		$bikeLocPLZOrt .= ' ';
	}
	$bikeLocPLZOrt .= $bike['bikeLocOrt'];
}

if (isset($bike['bikeLocCountry']) && isset($lang['COUNTRY'][$bike['bikeLocCountry']])){
	if ($bikeLoc != ''){
		$bikeLoc .= ', ';
	}
	$bikeLoc .= ' '.$lang['COUNTRY'][$bike['bikeLocCountry']];
	$bikeLocCountry = $bike['bikeLocCountry'];
}

if ((isset($bike['bikeLocPLZ']) && ($bike['bikeLocPLZ'] != null))
	|| (isset($bike['bikeLocOrt']) && ($bike['bikeLocOrt'] != null))
	|| ($bikeLocCountry != null)
	){
		
	$bikeLocc = '	<li><strong>'.$lang['TXT_114'].'</strong></li>
				<li><div id="map"></div></li>';
	$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').
									'	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/map.js"></script>'
										);
										//<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
																									
	$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
								.'	var $gl_mapLocPLZ = \''.$bike['bikeLocPLZ'].'\';
									var $gl_mapLocCountry = \''.$bikeLocCountry.'\';
									'
					);
$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/map.css" />');
	
}
$tmpl -> setValue('BIKE_LOC', $bikeLoc);

//Set userTel
$userTel = '';
if (isset($bike['userTel1']) && ($strIsEmptyFilter -> filter($bike['userTel1']) == false)){
	//$userTel .= '<li><span>'.$lang['TXT_80'].'</span>'.$bike['userTel1'].'</li>';
	$userTel .= '<li>'.$lang['TXT_80'].': '.$bike['userTel1'].'</li>';
}
if (isset($bike['userTel2']) && ($strIsEmptyFilter -> filter($bike['userTel2']) == false)){
	//$userTel .= '<li><span>'.$lang['TXT_80'].'</span>'.$bike['userTel2'].'</li>';
	$userTel .= '<li>'.$lang['TXT_80'].': '.$bike['userTel2'].'</li>';
}
$tmpl -> setValue('USER_TEL', $userTel);


$photoGallery = null;
if (isset($bike['bikePics']) && is_array($bike['bikePics']) && (count($bike['bikePics']) > 0)){
	$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES').'
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/photo_gallery.css" />');
	$this -> bike['jsActive'] =true;
	if (isset($this -> bike['jsActive'])){ 
		$photoGallery .= '
						<a id="prev" href="#">&lt;</a>
						<a id="next" href="#">&gt;</a>
						<label><strong>{-TXT_98-}</strong></label> &nbsp;
						<div id="photoGallery">';
		//Set photo gallery
		$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES')
										.'
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/carouFredSel_4_4_1.js"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/prettyPhoto.js"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/photoGallery.js"></script>'
										);
		$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
										.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/prettyPhoto.css" />');
	
		//Set javascript gallery image pattern																
		$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
									.'var $gl_sysPicPath = \''.System_Properties::SYS_PIC_PATH.'\';'
						);
						
		foreach($bike['bikePics'] AS $bikePic){
			$picURI = '/pic/'.System_Properties::BIKE_ABRV.'_'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg';
			if (!file_exists('.'.$picURI)){
				$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			}
			
			//$photoGallery .= '	<a rel="prettyPhoto[pp_gal]" href="/pic/'.System_Properties::BIKE_ABRV.'_'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg">ss</a>';
			$photoGallery .= '	<div><a rel="prettyPhoto[pp_gal]" href="'.$picURI.'"><img src="'.$picURI.'"/></a></div>';///pic/'.System_Properties::BIKE_ABRV.'_'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg
			if ($og['IMAGE'] == ''){
				$og['IMAGE'] = $picURI;//'/pic/'.System_Properties::BIKE_ABRV.'_'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg';
			}
			//<a href="/bike/'.$bike['bikeID'].'/'.$bike['page'].'/vp/'.$bikePic['vPicID'].'" target="_blank"><img src="/pic/'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg"/></a>
		}
		$photoGallery .= '
						</div>';			
	}
	else{	
		$maxBikePic = count($bike['bikePics']);
		
		if($maxBikePic > System_Properties::MAX_PHOTO_GALLERY){
			$photoGallery = '
				<form action="/bike/'.$bike['bikeID'].'/'.$bike['page'].'/pid/'.$bike['lastPicPID'].'" method="post">
					<input type="submit" name="prev" value="&lt;"/>
					<input type="submit" name="next" value="&gt;"/>
				</form>'.$photoGallery;
		}
		
		$photoGallery .= '
						<div id="photoGalleryCont"><ul id="photoGallery">';
		
		if (isset($bike['next']) && ($bike['next'] != null)){
			$bike['lastPicPID']++;
		}
		else if (isset($bike['prev']) && ($bike['prev'] != null)){
			$bike['lastPicPID']--;
			if ($bike['lastPicPID'] <= 0){
				$bike['lastPicPID'] = 0;
			}
		}
		$start = $bike['lastPicPID'] * System_Properties::MAX_PHOTO_GALLERY;
		if ($start > $maxBikePic){
			$bike['lastPicPID']--;
			if ($bike['lastPicPID'] <= 0){
				$bike['lastPicPID'] = 0;
			}
			$start = $bike['lastPicPID'] * System_Properties::MAX_PHOTO_GALLERY;
		}
		$end = $start + System_Properties::MAX_PHOTO_GALLERY;
		if($end > $maxBikePic){
			$end = $maxBikePic;
		}
		
		for($i = $start; $i < $end; $i++){
			if(isset($bike['bikePics'][$i])){
				$bikePic = $bike['bikePics'][$i];
				$photoGallery .= '	<li class="photo">
										<a href="/bike/pic/pid/'.$bikePic['vPicID'].'" target="_blank"><img src="/pic/'.System_Properties::BIKE_ABRV.'_'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg"/></a>
									</li>';
				//<a href="/bike/'.$bike['bikeID'].'/'.$bike['page'].'/vp/'.$bikePic['vPicID'].'" target="_blank"><img src="/pic/'.$bikePic['vID'].'_'.$bikePic['vPicID'].'.jpeg"/></a>
			}else{
				break;
			}
		}
		$photoGallery .= '
				</ul>
				</div>';
	}
}/*
else{
	$photoGallery = '<div id="photoGalleryCont"><ul id="photoGallery">
						<li class="photo">
							<img src="'.System_Properties::NO_PIC_PATH.'"/>
						</li>
					</ul>
					</div>';
}
*/
if ($photoGallery != null){
	$photoGallery = $photoGallery;
}
$tmpl -> setValue('PHOTO_GALLERY', $photoGallery);



//FORM_ACTION_PARAM
$tmpl -> setValue('FORM_ACTION_PARAM', '/'.$bike['bikeID'].'/'.$bike['page']);
//BIKE_ID
$tmpl -> setValue('BIKE_ID', $bike['bikeID']);
//SEARCH_RES_PAGE
$tmpl -> setValue('SEARCH_RES_PAGE', $bike['page']);

/*
//USER_LINK_ADS_VAL
$userLinkAdsVal = '';
if (isset($bike['userLinkAds']) && ($bike['userLinkAds'] == 1)){
	$userLinkAdsVal = '<li><a href="/dealer/'.$bike['userID'].'">>>>> '.$lang['TXT_121'].'</a></li>';
}
$tmpl -> setValue('USER_LINK_ADS_VAL', $userLinkAdsVal);
*/

//DELEAR_ID
$dealerID = $bike['userID'];
$tmpl -> setValue('DEALER_ID', $dealerID);


//EMAIL_NAME
$emailName = '';
if (is_array($p) && isset($p['emailName'])){
	$emailName = $p['emailName'];
}
$tmpl -> setValue('EMAIL_NAME', $emailName);

//EMAIL_ADDRESS
$emailAddress = '';
if (is_array($p) && isset($p['emailAddress'])){
	$emailAddress = $p['emailAddress'];
}
$tmpl -> setValue('EMAIL_ADDRESS', $emailAddress);


//EMAIL_TEXT
$emailText = '';
if (is_array($p) && isset($p['emailText'])){
	$emailText = $p['emailText'];
}
$tmpl -> setValue('EMAIL_TEXT', $emailText);


//CAPTCHA_CODE
if (is_array($p) && isset($p['captcha_code'])){
	$captchaCode = $p['captcha_code'];
}
$captchaCode = '';
$tmpl -> setValue('CAPTCHA_CODE', $captchaCode);

//DEALER
$dealerVal = '';
if (is_array($bike) && isset($bike['userAds']) && ($bike['userAds'] != 3)){
	$dealerVal = ' | <a href="/dealer/{-DEALER_ID-}/bike">{-TXT_189-}</a>';
}
$tmpl -> setValue('DEALER', $dealerVal);

//EXT_LINK
$extLink = '';
if (is_array($bike) && isset($bike['extLink']) && ($strIsEmptyFilter -> filter($bike['extLink']) == false)){
	$extLink .= '<a href="/index/redirect/vt/'.System_Properties::BIKE_ABRV.'/vi/'.$bike['bikeID'].'" target="_blank">'.$lang['TXT_257'].'</a>';
}
$tmpl -> setValue('EXT_LINK', $extLink);

//Bookmark
$bookmarkVal = '';
if (isset($bookmark) && ($bookmark == true)){
	$bookmarkVal = '| <a href="/bike/bookmark/id/{-BIKE_ID-}/p/{-SEARCH_RES_PAGE-}">{-TXT_120-}</a>';
}
$tmpl -> setValue('BOOKMARK', $bookmarkVal);	

//FB_DATA_HREF
$tmpl -> setValue('FB_DATA_HREF', 'http://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']);

//FB XMLNS
$tmpl -> setValue('XMLNS', $tmpl -> getValue('XMLNS').' xmlns:og="http://ogp.me/ns#" ');
$tmpl -> setValue('XMLNS', $tmpl -> getValue('XMLNS').' xmlns:fb="http://www.facebook.com/2008/fbml" '); 

//OPEN GRAPH TAGS
$og['TITLE'] = $bike['bikeBrandName'].' '.$bikeModel;//.' '.$bikePriceVal;
if(is_array($system) && isset($system['sysSiteName'])){
	$og['URL'] = 'http://'.$system['sysSiteName'].$_SERVER['REQUEST_URI'];
	$og['SITE_NAME'] = $system['sysSiteName'];	
	$og['TITLE'] = $system['sysSiteName'].' - '.$og['TITLE'];
	if ($og['IMAGE'] != ''){
		$og['IMAGE'] = 'http://'.$system['sysSiteName'].'.de'.$og['IMAGE'];
	}else{
		$og['IMAGE'] = 'http://'.$system['sysSiteName'].'.de/sysPic/logo24.png';
	}
}
$og['TITLE'] = str_ireplace('&euro;', 'EUR', $og['TITLE']);

//<meta property="og:url" content="'.$og['URL'].'"/>
$tmpl -> setValue('OPEN_GRAPH', '	<meta property="og:title" content="'.$og['TITLE'].'"/>
									<meta property="og:type" content="'.$og['TYPE'].'"/>
									<meta property="og:image" content="'.$og['IMAGE'].'"/>
									<meta property="og:site_name" content="'.$og['SITE_NAME'].'"/>
									<meta property="og:description" content="'.implode(', ',$og['SITE_DESC']).'"/>			
									<meta property="fb:admins" content="'.implode(',', System_Properties::$FB_ADMINS).'"/>
									');
$tmpl -> setValue('META_DESCRIPTION', implode(', ',$og['SITE_DESC']));

$title = implode(', ',$og['SITE_DESC']);
$title = str_ireplace('&euro;', 'EUR', $title).' | '.$tmpl -> getValue('TITLE');
$tmpl -> setValue('TITLE', $title);

$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}

$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();

//<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
?>