<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This is the view of PKW Index. It implements the search mask
 *********************************************************************************/
$tmpl = $this -> tmpl;

$tmpl -> readTmplFile('CONTENT', 'default/bike/index.html');
echo $this -> tmpl -> render();
?>
