<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This file specify the view for registration
 *********************************************************************************/
include_once('default/views/helpers/func_pageCounter.phtml');
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$user = $this -> user;
$lang = $this -> lang;
$actPage = $this -> page;

$bookmarksCarAds = $this -> bookmarksCarAds;
$bookmarksBikeAds = $this -> bookmarksBikeAds;
$bookmarskTruckAds = $this -> bookmarksTruckAds;

$vehicleType = $this -> vehicleType;

$formatStr2Num = new FormatSt2Num();
$isEmptyString = new FilterIsEmptyString();

$tmpl -> readTmplFile('CONTENT', 'default/member/index.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'	<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/search.css" />
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/myParkMenu.css" />
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/member.css" />
									');


//NUM_CAR_ADS
$numCarAds = '0';
if (isset($this->numCarAds) && is_array($this -> numCarAds) && isset($this -> numCarAds['totalAds'])){
	$numCarAds = $this -> numCarAds['totalAds'];
}
$tmpl -> setValue('NUM_CAR_ADS', $numCarAds);

//NUM_BIKE_ADS
$numBikeAds = '0';
if (isset($this->numBikeAds) && is_array($this -> numBikeAds) && isset($this -> numBikeAds['totalAds'])){
	$numBikeAds = $this -> numBikeAds['totalAds'];
}
$tmpl -> setValue('NUM_BIKE_ADS', $numBikeAds);

//NUM_TRUCK_ADS
$numTruckAds = '0';
if (isset($this->numTruckAds) && is_array($this -> numTruckAds) && isset($this -> numTruckAds['totalAds'])){
	$numTruckAds = $this -> numTruckAds['totalAds'];
}
$tmpl -> setValue('NUM_TRUCK_ADS', $numTruckAds);

$searchResEntryTMPL = $tmpl -> readFile('default/myads.html');
$searchResEntryTMPL = $tmpl -> replace(	'MY_ADS_MENU',
										'<a href="{-PARK_OUT_URL-}">{-TXT_172-}</a>',
										$searchResEntryTMPL
										);
$tmpl -> setValue('JUMP', '#carDel');

//BOOKMARK_ADS
$bookmarksAds = '';		
$numOfAds = 0;

//Add bookmarked car advertisements										
if (isset($bookmarksCarAds) && is_array($bookmarksCarAds)){
	isset($bookmarksCarAds['totalAds']) ? $numOfAds = $numOfAds + $bookmarksCarAds['totalAds']:'';
	
	foreach($bookmarksCarAds['carAds'] AS $key => $kValue){
		if (is_array($kValue) && isset($kValue['carID'])){
			$parkOutUrl = '/member/index/v/'.$vehicleType.'/id/'.$kValue['carID'].'/d/1';
			
			//Determine car pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($kValue['carPics']) && is_array($kValue['carPics'])){
				foreach ($kValue['carPics'] AS $carPic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::CAR_ABRV.'_'.$kValue['carID'].'_'.$carPic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine car brand
			$carBrand = $kValue['carBrandName'];
			if (isset($kValue['carModelName'])){
				$carBrand .= ' '.$kValue['carModelName'];
			}
			
			$adDetail = '';
			
			//carPrice
			if (isset($kValue['carPrice'])){
				$adDetail .= $formatStr2Num -> filter($kValue['carPrice']);
				//carPriceCurr
				if (isset($kValue['carPriceCurr']) && isset($lang['TXT_74'][$kValue['carPriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$kValue['carPriceCurr']];
				}
				
				//carPriceType
				if (isset($kValue['carPriceType']) && isset($lang['TXT_70'][$kValue['carPriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$kValue['carPriceType']];
				}
				
				$adDetail .= ', ';
			}
			
			//carKM
			if (isset($kValue['carKM'])){
				$adDetail .= $formatStr2Num -> filter($kValue['carKM']).' ';
				if (isset($lang['TXT_75'][$kValue['carKMType']])){
					$adDetail .= $lang['TXT_75'][$kValue['carKMType']];
				}
				$adDetail .= ', ';
			}
			
			//carPower
			if (isset($kValue['carPower'])){
				//0 = kW
				if(isset($kValue['carPowerType']) && ($kValue['carPowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($kValue['carPower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['carPower']*90/66).' '.$lang['TXT_72'][0].')';
				}
				//1 = PS
				elseif(isset($kValue['carPowerType']) && ($kValue['carPowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($kValue['carPower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['carPower']).' '.$lang['TXT_72'][1].')';
				}
				$adDetail .= ', ';				
			}
			
			//carEZ
			if (isset($kValue['carEZM']) && isset($kValue['carEZY'])){
				$adDetail .= $kValue['carEZM'].'/'.$kValue['carEZY'];
			}
			
			if ($adDetail != ''){
				//car
				$adDetail .= '<br/>';
				if (isset($kValue['userNName']) && isset($kValue['userVName'])){
					$adDetail .= $kValue['userNName'].' '.$kValue['userVName'];
				}
				
				//carLocPLZ, carLocOrt
				if (isset($kValue['carUserPLZ']) || isset($kValue['carLocOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['carLocPLZ']) == false){
						$adDetail .= ' '.$kValue['carLocPLZ'];
					}
					if ($isEmptyString -> filter($kValue['carLocOrt']) == false){
						$adDetail .= ' '.$kValue['carLocOrt'];
					}
				}elseif (isset($kValue['userPLZ']) || isset($kValue['userOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['userPLZ']) == false){
						$adDetail .= ' '.$kValue['userPLZ'];
					}
					if ($isEmptyString -> filter($kValue['userOrt']) == false){
						$adDetail .= ' '.$kValue['userOrt'];
					}
				}
			}
			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'PARK_OUT_URL',
												$parkOutUrl,
												$searchResEntry
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/car/'.$kValue['carID'],
												//'/car/'.$kValue['carID'].'/'.$this -> carAds['actPage'],
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$carBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$bookmarksAds .= $searchResEntry;

		
			//$myCarAds .= '<a href="/car/mycardetail/id/'.$kValue['carID'].'">'.$kValue['carBrandName'].'</a><br/>';
		}
	}
	/*
	foreach($bookmarksCarAds as $key=>$kVal){
		if (isset($kVal['carID'])){
			$bookmarksAds .= '<tr>
								<td><a href="/car/'.$kVal['carID'].'" target="blank">'.$kVal['carBrandName'].'</a></td>
								<td><a href="">'.$lang['TXT_172'].'</a></td>
							</tr>';
		}
	}
	*/
}		
//Add bookmarked bike advertisements										
if (isset($bookmarksBikeAds) && is_array($bookmarksBikeAds)){
	isset($bookmarksAds['totalAds']) ? $numOfAds = $numOfAds + $bookmarksBikeAds['totalAds']:'';
		
	foreach($bookmarksBikeAds AS $key => $kValue){
		if (is_array($kValue) && isset($kValue['bikeID'])){
			$parkOutUrl = '/member/index/v/'.$vehicleType.'/id/'.$kValue['bikeID'].'/d/1';
			
			//Determine bike pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($kValue['bikePics']) && is_array($kValue['bikePics'])){
				foreach ($kValue['bikePics'] AS $bikePic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::BIKE_ABRV.'_'.$kValue['bikeID'].'_'.$bikePic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine bike brand
			$bikeBrand = $kValue['bikeBrandName'];
			if (isset($kValue['bikeModelName'])){
				$bikeBrand .= ' '.$kValue['bikeModelName'];
			}
			
			$adDetail = '';
			
			//bikePrice
			if (isset($kValue['bikePrice'])){
				$adDetail .= $formatStr2Num -> filter($kValue['bikePrice']);
				//bikePriceCurr
				if (isset($kValue['bikePriceCurr']) && isset($lang['TXT_74'][$kValue['bikePriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$kValue['bikePriceCurr']];
				}
				
				//bikePriceType
				if (isset($kValue['bikePriceType']) && isset($lang['TXT_70'][$kValue['bikePriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$kValue['bikePriceType']];
				}
				
				$adDetail .= ', ';
			}
			
			//bikeKM
			if (isset($kValue['bikeKM'])){
				$adDetail .= $formatStr2Num -> filter($kValue['bikeKM']).' ';
				if (isset($lang['TXT_75'][$kValue['bikeKMType']])){
					$adDetail .= $lang['TXT_75'][$kValue['bikeKMType']];
				}
				$adDetail .= ', ';
			}
			
			//bikePower
			if (isset($kValue['bikePower'])){
				//0 = kW
				if(isset($kValue['bikePowerType']) && ($kValue['bikePowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($kValue['bikePower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['bikePower']*90/66).' '.$lang['TXT_72'][0].')';
				}
				//1 = PS
				elseif(isset($kValue['bikePowerType']) && ($kValue['bikePowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($kValue['bikePower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['bikePower']).' '.$lang['TXT_72'][1].')';
				}
				$adDetail .= ', ';				
			}
			
			//bikeEZ
			if (isset($kValue['bikeEZM']) && isset($kValue['bikeEZY'])){
				$adDetail .= $kValue['bikeEZM'].'/'.$kValue['bikeEZY'];
			}
			
			if ($adDetail != ''){
				//bike
				$adDetail .= '<br/>';
				if (isset($kValue['userNName']) && isset($kValue['userVName'])){
					$adDetail .= $kValue['userNName'].' '.$kValue['userVName'];
				}
				
				//bikeLocPLZ, bikeLocOrt
				if (isset($kValue['bikeUserPLZ']) || isset($kValue['bikeLocOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['bikeLocPLZ']) == false){
						$adDetail .= ' '.$kValue['bikeLocPLZ'];
					}
					if ($isEmptyString -> filter($kValue['bikeLocOrt']) == false){
						$adDetail .= ' '.$kValue['bikeLocOrt'];
					}
				}elseif (isset($kValue['userPLZ']) || isset($kValue['userOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['userPLZ']) == false){
						$adDetail .= ' '.$kValue['userPLZ'];
					}
					if ($isEmptyString -> filter($kValue['userOrt']) == false){
						$adDetail .= ' '.$kValue['userOrt'];
					}
				}
			}
			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'PARK_OUT_URL',
												$parkOutUrl,
												$searchResEntry
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/bike/'.$kValue['bikeID'],
												//'/bike/'.$kValue['bikeID'].'/'.$this -> bikeAds['actPage'],
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$bikeBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$bookmarksAds .= $searchResEntry;

		
			//$myBikeAds .= '<a href="/bike/mybikedetail/id/'.$kValue['bikeID'].'">'.$kValue['bikeBrandName'].'</a><br/>';
		}
	}
	/*
	foreach($bookmarksBikeAds as $key=>$kVal){
		if (isset($kVal['bikeID'])){
			$bookmarksAds .= '<tr>
								<td><a href="/bike/'.$kVal['bikeID'].'" target="blank">'.$kVal['bikeBrandName'].'</a></td>
								<td><a href="">'.$lang['TXT_172'].'</a></td>
							</tr>';
		}
	}*/
}		
//Add bookmarked truck advertisements										
if (isset($bookmarksTruckAds) && is_array($bookmarksTruckAds)){
	isset($bookmarksAds['totalAds']) ? $numOfAds = $numOfAds + $bookmarksTruckAds['totalAds']:'';
	
	foreach($bookmarksTruckAds AS $key => $kValue){
		if (is_array($kValue) && isset($kValue['truckID'])){
			$parkOutUrl = '/member/index/v/'.$vehicleType.'/id/'.$kValue['truckID'].'/d/1';
			
			//Determine truck pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($kValue['truckPics']) && is_array($kValue['truckPics'])){
				foreach ($kValue['truckPics'] AS $truckPic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::TRUCK_ABRV.'_'.$kValue['truckID'].'_'.$truckPic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine truck brand
			$truckBrand = $kValue['truckBrandName'];
			if (isset($kValue['truckModelName'])){
				$truckBrand .= ' '.$kValue['truckModelName'];
			}
			
			$adDetail = '';
			
			//truckPrice
			if (isset($kValue['truckPrice'])){
				$adDetail .= $formatStr2Num -> filter($kValue['truckPrice']);
				//truckPriceCurr
				if (isset($kValue['truckPriceCurr']) && isset($lang['TXT_74'][$kValue['truckPriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$kValue['truckPriceCurr']];
				}
				
				//truckPriceType
				if (isset($kValue['truckPriceType']) && isset($lang['TXT_70'][$kValue['truckPriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$kValue['truckPriceType']];
				}
				
				$adDetail .= ', ';
			}
			
			//truckKM
			if (isset($kValue['truckKM'])){
				$adDetail .= $formatStr2Num -> filter($kValue['truckKM']).' ';
				if (isset($lang['TXT_75'][$kValue['truckKMType']])){
					$adDetail .= $lang['TXT_75'][$kValue['truckKMType']];
				}
				$adDetail .= ', ';
			}
			
			//truckPower
			if (isset($kValue['truckPower'])){
				//0 = kW
				if(isset($kValue['truckPowerType']) && ($kValue['truckPowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($kValue['truckPower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['truckPower']*90/66).' '.$lang['TXT_72'][0].')';
				}
				//1 = PS
				elseif(isset($kValue['truckPowerType']) && ($kValue['truckPowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($kValue['truckPower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['truckPower']).' '.$lang['TXT_72'][1].')';
				}
				$adDetail .= ', ';				
			}
			
			//truckEZ
			if (isset($kValue['truckEZM']) && isset($kValue['truckEZY'])){
				$adDetail .= $kValue['truckEZM'].'/'.$kValue['truckEZY'];
			}
			
			if ($adDetail != ''){
				//truck
				$adDetail .= '<br/>';
				if (isset($kValue['userNName']) && isset($kValue['userVName'])){
					$adDetail .= $kValue['userNName'].' '.$kValue['userVName'];
				}
				
				//truckLocPLZ, truckLocOrt
				if (isset($kValue['truckUserPLZ']) || isset($kValue['truckLocOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['truckLocPLZ']) == false){
						$adDetail .= ' '.$kValue['truckLocPLZ'];
					}
					if ($isEmptyString -> filter($kValue['truckLocOrt']) == false){
						$adDetail .= ' '.$kValue['truckLocOrt'];
					}
				}elseif (isset($kValue['userPLZ']) || isset($kValue['userOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['userPLZ']) == false){
						$adDetail .= ' '.$kValue['userPLZ'];
					}
					if ($isEmptyString -> filter($kValue['userOrt']) == false){
						$adDetail .= ' '.$kValue['userOrt'];
					}
				}
			}
			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'PARK_OUT_URL',
												$parkOutUrl,
												$searchResEntry
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/truck/'.$kValue['truckID'],
												//'/truck/'.$kValue['truckID'].'/'.$this -> truckAds['actPage'],
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$truckBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$bookmarksAds .= $searchResEntry;

		
			//$myTruckAds .= '<a href="/truck/mytruckdetail/id/'.$kValue['truckID'].'">'.$kValue['truckBrandName'].'</a><br/>';
		}
	}
	/*
	foreach($bookmarksTruckAds as $key=>$kVal){
		if (isset($kVal['truckID'])){
			$bookmarksAds .= '<tr>
								<td><a href="/truck/'.$kVal['truckID'].'" target="blank">'.$kVal['truckBrandName'].'</a></td>
								<td><a href="">'.$lang['TXT_172'].'</a></td>
							</tr>';
		}
	}
	*/
}

$bookmarksAds .= pageCounter($numOfAds, '/member/index/v/'.$vehicleType.'/p/', $actPage, 1);

$tmpl -> setValue('BOOKMARK_ADS', $bookmarksAds);

/*
	<a href="/member/chgprofile">{-TXT_154-}</a>
	<a href="/member/delaccount">{-TXT_155-}</a>*/


//INFO
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}

$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();


?>
