<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This file specify the view for registration
 *********************************************************************************/
include_once('default/views/helpers/func_pageCounter.phtml');
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$user = $this -> user;
$lang = $this -> lang;
$carAds = $this -> carAds;
$formatStr2Num = new FormatSt2Num();
$isEmptyString = new FilterIsEmptyString();

$tmpl -> readTmplFile('CONTENT', 'default/member/mycarads.html');

include_once('default/views/scripts/car/myCarQS.phtml');
$tmpl -> setValue('QS_FORM_ACTION', '/member/mycarads');
$tmpl -> setValue('QS_HEADING', $lang['TXT_197']);

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/mycaradsdetail.css" />');

$searchResEntryTMPL = $tmpl -> readFile('default/myads.html');
$searchResEntryTMPL = $tmpl -> replace(	'MY_ADS_MENU',
										'<a href="{-BRAND_URL-}">{-TXT_144-}</a> | <a href="{-BRAND_URL-}{-JUMP-}">{-TXT_143-}</a>',
										$searchResEntryTMPL
										);
$tmpl -> setValue('JUMP', '#carDel');

$myCarAds = '';
if (is_array($carAds) && isset($carAds['carAds'])){
	foreach($carAds['carAds'] AS $key => $kValue){
		if (is_array($kValue) && isset($kValue['carID'])){
			
			//Determine car pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($kValue['carPics']) && is_array($kValue['carPics'])){
				foreach ($kValue['carPics'] AS $carPic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::CAR_ABRV.'_'.$kValue['carID'].'_'.$carPic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine car brand
			$carBrand = $kValue['carBrandName'];
			if (isset($kValue['carModelName'])){
				$carBrand .= ' '.$kValue['carModelName'];
			}
			
			$adDetail = '';
			
			//carPrice
			if (isset($kValue['carPrice'])){
				if(isset($kValue['mwst']) && ($kValue['mwst'] == 1)
					&& isset($kValue['mwstSatz']) && ($kValue['mwstSatz'] > 0)){
					$kValue['carPrice'] = $kValue['carPrice'] * ($kValue['mwstSatz'] / 100 + 1);
				}
				$adDetail .= $formatStr2Num -> filter($kValue['carPrice']);
				//carPriceCurr
				if (isset($kValue['carPriceCurr']) && isset($lang['TXT_74'][$kValue['carPriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$kValue['carPriceCurr']];
				}
				
				//carPriceType
				if (isset($kValue['carPriceType']) && isset($lang['TXT_70'][$kValue['carPriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$kValue['carPriceType']];
				}
				
				$adDetail .= ', ';
			}
			
			//carKM
			if (isset($kValue['carKM'])){
				$adDetail .= $formatStr2Num -> filter($kValue['carKM']).' ';
				if (isset($lang['TXT_75'][$kValue['carKMType']])){
					$adDetail .= $lang['TXT_75'][$kValue['carKMType']];
				}
				$adDetail .= ', ';
			}
			
			//carPower
			if (isset($kValue['carPower'])){
				//0 = kW
				if(isset($kValue['carPowerType']) && ($kValue['carPowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($kValue['carPower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['carPower']*90/66).' '.$lang['TXT_72'][0].')';
				}
				//1 = PS
				elseif(isset($kValue['carPowerType']) && ($kValue['carPowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($kValue['carPower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($kValue['carPower']).' '.$lang['TXT_72'][1].')';
				}
				$adDetail .= ', ';				
			}
			
			//Set CAR_EZ
			if($kValue['carEZY'] == 9999){
				$adDetail .= $lang['V_STATE'][0];
			}
			elseif (($kValue['carEZM'] > 0) && ($kValue['carEZY'] > 0)){
				$adDetail .= $kValue['carEZM'].'/'.$kValue['carEZY'];
			}
			
			if ($adDetail != ''){
				
				//carLocPLZ, carLocOrt
				$carLoc = '';
				if (isset($kValue['carUserPLZ']) || isset($kValue['carLocOrt'])){
					$carLoc .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['carLocPLZ']) == false){
						$carLoc .= ' '.$kValue['carLocPLZ'];
					}
					if ($isEmptyString -> filter($kValue['carLocOrt']) == false){
						$carLoc .= ' '.$kValue['carLocOrt'];
					}
				}elseif (isset($kValue['userPLZ']) || isset($kValue['userOrt'])){
					$carLoc .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($kValue['userPLZ']) == false){
						$carLoc .= ' '.$kValue['userPLZ'];
					}
					if ($isEmptyString -> filter($kValue['userOrt']) == false){
						$carLoc .= ' '.$kValue['userOrt'];
					}
				}
				
				//car
				$adDetail .= '<br/>';				
				if (isset($kValue['userFirm']) && ($kValue['userFirm'] != '')){
					$adDetail .= $kValue['userFirm'].$carLoc;
				}else{
					$adDetail .= substr($carLoc,2);
				}/*
				elseif (isset($kValue['userNName']) && isset($kValue['userVName'])){
					$adDetail .= $kValue['userNName'].' '.$kValue['userVName'];
				}*/
			}
			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/car/mycardetail/id/'.$kValue['carID'],
												//'/car/'.$kValue['carID'].'/'.$this -> carAds['actPage'],
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$carBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$myCarAds .= $searchResEntry;

		
			//$myCarAds .= '<a href="/car/mycardetail/id/'.$kValue['carID'].'">'.$kValue['carBrandName'].'</a><br/>';
		}
	}
	$myCarAds .= pageCounter($carAds['totalAds'], '/member/mycarads/', $carAds['actPage'], $carAds['numAds']);
}
$tmpl -> setValue('MY_CAR_ADS', $myCarAds);

//INFO
/*
$infoVal = '';
if (isset($this -> error)){
	$infoVal .= $this -> error;
}
if (isset($this -> info)){
	$infoVal .= $this -> info;
}
$tmpl -> setValue('INFO', $infoVal);
*/
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}

$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();


?>
