<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This file specify the view for registration
 *********************************************************************************/
$tmpl = $this -> tmpl;
$user = $this -> user;

$tmpl -> readTmplFile('CONTENT', 'default/member/register.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'	<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/register.css" />
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/member.css" />');

//USER_NNAME_VAL
$userNNameVal = '';
if (isset($user['userNName'])){
	$userNNameVal = $user['userNName'];
}
$tmpl -> setValue('USER_NNAME_VAL', $userNNameVal);

//USER_VNAME_VAL
$userVNameVal ='';
if (isset($user['userVName'])){
	$userVNameVal = $user['userVName'];
}
$tmpl -> setValue('USER_VNAME_VAL', $userVNameVal);

//USER_EMAIL_VAL
$userEMailVal ='';
if (isset($user['userEMail'])){
	$userEMailVal = $user['userEMail'];
}
$tmpl -> setValue('USER_EMail_VAL', $userEMailVal);

//USER_AGB_VAL 
$userAGBVal = '';
if (isset($user['userAGB'])){
	$userAGBVal = 'checked';
}
$tmpl -> setValue('USER_AGB_VAL', $userAGBVal);

//USER_NEWS_VAL
$userNewsVal = '';
if (isset($user['userNews'])){
	$userNewsVal = 'checked';
}
$tmpl -> setValue('USER_NEWS_VAL', $userNewsVal);

//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();


?>
