<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This is the view of INDEX
 *********************************************************************************/

$tmpl = $this -> tmpl;

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/index.css" />'
				);
				
$tmpl -> readTmplFile('CONTENT', 'default/car/index.html');

//INFO
$infoVal = '';
if (isset($this -> error)){
	$infoVal .= $this -> error;
}
if (isset($this -> info)){
	$infoVal .= $this -> info;
}
$tmpl -> setValue('INFO', $infoVal);


echo $this -> tmpl -> render();

?>
