<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$searchParam = $this -> searchParam;

include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/user/usersearchbox.phtml');

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/user/index.html');	

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/user.css" />');	
//$tmpl -> readTmplFile('USER_SEARCH_BOX', System_Properties::ADMIN_MOD_PATH.'/user/usersearch_box.html');	

//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);
echo $tmpl -> render();
?>
