<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for bike maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$bikeVcat = $this -> bikeVcat;
$bikeVcatParent = $this -> bikeVcatParent;
$bikeVcatAll = $this -> bikeVcatAll;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/bike/bikecatedit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="tcat/css" href="'.System_Properties::ADMIN_CSS_PATH.'/bike.css" />
								<link rel="stylesheet" type="tcat/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');
/*							
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', '	<script type="tcat/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/jq_141_min.js"></script>
								<script type="tcat/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/cs.js"></script>');	

*/
//set V_CAT new
if (isset($lang['V_CAT'][$bikeVcat['vcatID']])){
	$tmpl -> setValue('V_CAT_NEW', $lang['V_CAT'][$bikeVcat['vcatID']]);
	$tmpl -> setValue('BIKE_CAT_ID', $bikeVcat['bikeCatID']);
}

//set V_CAT_PARENT
//process vcat parent list and bike cat list
$vcatParent = '<select name="vcatParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($bikeVcatAll)){
	foreach($bikeVcatAll as $key => $vpValue){
		if (isset($lang['V_CAT'][$vpValue['vcatID']])){
			$vcatParent .= '<option value="'.$vpValue['bikeCatID'].'" class="level'.$vpValue['level'].'"';
			if(isset($bikeVcatParent['bikeCatID']) && ($bikeVcatParent['bikeCatID'] == $vpValue['bikeCatID'])){
				$vcatParent .= ' selected ';
			}
			$vcatParent .= '>'.$lang['V_CAT'][$vpValue['vcatID']].'</option>';
		}
	}
}
$vcatParent .= '</select>';
$tmpl -> setValue('V_CAT_PARENT', $vcatParent);


//INFO
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $tmpl -> render();
?>
