<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for car maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/bike/bikeQuickSearch.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$searchParam = $this -> searchParam;
$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/bike/index.html');	
	

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/bike.css" />');
								
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').'
								<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/bs.js"></script>');	




//INFO
$info = '';
if (isset($this -> error)){
	$info = $this -> error;
}
if (isset($this -> info)){
	$info = $this -> info;
}
$tmpl -> setValue('INFO', $info);

echo $tmpl -> render();
?>
 