<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for car maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/car/carQuickSearch.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$carVext = $this -> carVext;
$carVextParent = $this -> carVextParent;
$carVextAll = $this -> carVextAll;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/car/carextraedit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/car.css" />
								<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');
	/*							
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', '	<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/jq_141_min.js"></script>
								<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/cs.js"></script>');	

*/
//set V_EXTRA new
if (isset($lang['V_EXTRA'][$carVext['vextID']])){
	$tmpl -> setValue('V_EXTRA_NEW', $lang['V_EXTRA'][$carVext['vextID']]);
	$tmpl -> setValue('CAR_EXTRA_ID', $carVext['carExtID']);
}

//set V_EXTRA_PARENT
//process vextra parent list and car extra list
$vextraParent = '<select name="vextraParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($carVextAll)){
	foreach($carVextAll as $key => $vpValue){
		if (isset($lang['V_EXTRA'][$vpValue['vextID']])){
			$vextraParent .= '<option value="'.$vpValue['carExtID'].'" class="level'.$vpValue['level'].'"';
			if(isset($carVextParent['carExtID']) && ($carVextParent['carExtID'] == $vpValue['carExtID'])){
				$vextraParent .= ' selected ';
			}
			$vextraParent .= '>'.$lang['V_EXTRA'][$vpValue['vextID']].'</option>';
		}
	}
}
$vextraParent .= '</select>';
$tmpl -> setValue('V_EXTRA_PARENT', $vextraParent);

//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $tmpl -> render();
?>
