<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100804
 * Desc:		This file specify the view for registration
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
include_once('default/views/helpers/func_pageCounter.phtml');
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$user = $this -> user;
$car = $this -> car;
$formatStr2Num = new FormatSt2Num();
$isEmptyString = new FilterIsEmptyString();

include_once('default/views/scripts/car/carQS.phtml');
include_once('default/views/scripts/dealer/dealer_menu.phtml');


$tmpl -> readTmplFile('CONTENT', 'default/dealer/car.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/dealer.css" />
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/search.css" />');


$quickSearch = $tmpl -> readTmplFile('QUICK_SEARCH', 'default/dealer/carQS.html');
$tmpl -> setValue('QS_FORM_ACTION', '/dealer/'.$user['userID'].'/car');
$tmpl -> setValue('QS_HEADING', $lang['TXT_197']);
								
							
//USER_FIRM
$userFirmVal = '';
if (isset($user['userFirm'])){
	$userFirmVal = $user['userFirm'];
}
if (($userFirmVal == '') && isset($user['userNName']) && isset($user['userVName'])){
	$userFirmVal .= $user['userNName'].' '.$user['userVName'];
}
$tmpl -> setValue('USER_FIRM_VAL', $userFirmVal);


$searchResEntryTMPL = $tmpl -> readFile('default/dealer/searchResEntry.html');
//Preparing search results and add this to the content
$carAds = '';
if (isset($car['carAds']) && is_array($car['carAds'])){
	$carAds = '<div class="search_res">';
	foreach ($car['carAds'] AS $carAd){
		if (isset($carAd['carID'])){
			//Determine car pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($carAd['carPics']) && is_array($carAd['carPics'])){
				foreach ($carAd['carPics'] AS $carPic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::CAR_ABRV.'_'.$carAd['carID'].'_'.$carPic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine car brand
			$carBrand = $carAd['carBrandName'];
			if (isset($carAd['carModelName'])){
				$carBrand .= ' '.$carAd['carModelName'];
			}
			
			$adDetail = '';
			
			//carPrice
			if (isset($carAd['carPrice'])){
				$adDetail .= $formatStr2Num -> filter($carAd['carPrice']);
				//carPriceCurr
				if (isset($carAd['carPriceCurr']) && isset($lang['TXT_74'][$carAd['carPriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$carAd['carPriceCurr']];
				}
				
				//carPriceType
				if (isset($carAd['carPriceType']) && isset($lang['TXT_70'][$carAd['carPriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$carAd['carPriceType']];
				}
				
				$adDetail .= ', ';
			}
			
			//carKM
			if (isset($carAd['carKM'])){
				$adDetail .= $formatStr2Num -> filter($carAd['carKM']).' ';
				if (isset($lang['TXT_75'][$carAd['carKMType']])){
					$adDetail .= $lang['TXT_75'][$carAd['carKMType']];
				}
				$adDetail .= ', ';
			}
			
			//carPower
			if (isset($carAd['carPower'])){
				//0 = kW
				if(isset($carAd['carPowerType']) && ($carAd['carPowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($carAd['carPower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($carAd['carPower']*90/66).' '.$lang['TXT_72'][0].')';
				}
				//1 = PS
				elseif(isset($carAd['carPowerType']) && ($carAd['carPowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($carAd['carPower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($carAd['carPower']).' '.$lang['TXT_72'][1].')';
				}
				$adDetail .= ', ';				
			}
			
			//Set CAR_EZ
			if($carAd['carEZY'] == 9999){
				$adDetail .= $lang['V_STATE'][0];
			}
			elseif (($carAd['carEZM'] > 0) && ($carAd['carEZY'] > 0)){
				$adDetail .= $carAd['carEZM'].'/'.$carAd['carEZY'];
			}
			
			if ($adDetail != ''){
				//car
				$adDetail .= '<br/>';
				if (isset($carAd['userFirm'])){
					$adDetail .= $carAd['userFirm'];
				}
				elseif (isset($carAd['userNName']) && isset($carAd['userVName'])){
					$adDetail .= $carAd['userNName'].' '.$carAd['userVName'];
				}
				
				//carLocPLZ, carLocOrt
				if (isset($carAd['carUserPLZ']) || isset($carAd['carLocOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($carAd['carLocPLZ']) == false){
						$adDetail .= ' '.$carAd['carLocPLZ'];
					}
					if ($isEmptyString -> filter($carAd['carLocOrt']) == false){
						$adDetail .= ' '.$carAd['carLocOrt'];
					}
				}elseif (isset($carAd['userPLZ']) || isset($carAd['userOrt'])){
					$adDetail .= ', '.$lang['TXT_114'].':';
					if ($isEmptyString -> filter($carAd['userPLZ']) == false){
						$adDetail .= ' '.$carAd['userPLZ'];
					}
					if ($isEmptyString -> filter($carAd['userOrt']) == false){
						$adDetail .= ' '.$carAd['userOrt'];
					}
				}
			}
			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/car/'.$carAd['carID'].'/'.$this -> carAds['actPage'],
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$carBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$carAds .= $searchResEntry;	
		}
	}
	$carAds .= '</div>';
	$carAds .= pageCounter($car['totalAds'], '/dealer/'.$user['userID'].'/car/', $car['actPage'], $car['numAds']);
}

$tmpl -> setValue('CAR_ADS', $carAds);


//INFO
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);
echo $this -> tmpl -> render();
?>
