<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100819
 * Desc:		This is the view of Truck insert confirmation section
 *********************************************************************************/
include_once('default/views/filters/FilterIsEmptyString.php');
include_once('default/views/filters/FormatStr2Num.php');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$truck = $this -> truck;
$truckCat = $this -> truckCat;
$fCheckSpace = new FilterIsEmptyString();
$str2NumFilter = new FormatSt2Num();
$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/truck.css" />
								<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/truck_insert.css" />
								<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/detail.css" />'
				);
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["adp"] = \'/admin\';
								g_arr["TRUCK_ID"] = \''.$truck['truckID'].'\';'
				);
				
$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/truck/insert3.html');

//TRUCK_ID
//$tmpl -> setValue('TRUCK_ID', $truck['truckID']);

//Set TRUCK_BRAND
$tmpl -> setValue('TRUCK_BRAND', $truck['truckBrandTxt']);

//Set TRUCK_MODEL
$truckModel = '';
if(isset($truck['truckModelTxt']) && ($truck['truckModelTxt'] != null)){
	$truckModel = $truck['truckModelTxt'];
}
$tmpl -> setValue('TRUCK_MODEL', $truckModel);

//SET TRUCK_MODEL_VAR
$truckModelVar = $lang['TXT_40'];
if (isset($truck['truckModelVar']) && ($truck['truckModelVar'] != null)){
	$truckModelVar = $truck['truckModelVar'];
}
$tmpl -> setValue('TRUCK_MODEL_VAR', $truckModelVar);

//Set TRUCK_PRICE
$truckPriceVal = '<table>';

if(isset($truck['mwst']) && ($truck['mwst'] == '1') && isset($truck['mwstSatz']) && in_array($truck['mwstSatz'],$lang['V_MWST'])){
	$truckPriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $truck['truckPrice']*($truck['mwstSatz']/100+1),
												'dec_place' => 0
												)
										). '{-TRUCK_PRICE_CURR-} ('.$lang['TXT_273'].')</td></tr>
					<tr><td>'.$str2NumFilter -> filter(array('val' => $truck['truckPrice'],
												'dec_place' => 0
												)
										).'{-TRUCK_PRICE_CURR-} ('.$lang['TXT_274'].')</td></tr>
					<tr><td>'.$truck['mwstSatz'].'% '.$lang['TXT_270'].'</td></tr>';
}
elseif(isset($truck['mwst']) && ($truck['mwst'] == '1')){
	$truckPriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $truck['truckPrice'],
												'dec_place' => 0
												)
										).'{-TRUCK_PRICE_CURR-}</td></tr>
					<tr><td>'.$lang['TXT_270'].'</td></tr>';
}else{
	$truckPriceVal .= '<tr><td>'.$str2NumFilter -> filter(array('val' => $truck['truckPrice'],
												'dec_place' => 0
												)
										).'{-TRUCK_PRICE_CURR-}</td></tr>
					<tr><td>'.$lang['TXT_275'].'</td></tr>';
}
$truckPriceVal .= '</table>';
$tmpl -> setValue('TRUCK_PRICE', $truckPriceVal);

$truckPriceCurr = '';
if (isset($lang['TXT_74'][$truck['truckPriceCurr']])){
	$truckPriceCurr = $lang['TXT_74'][$truck['truckPriceCurr']];
}
$tmpl -> setValue('TRUCK_PRICE_CURR', $truckPriceCurr);


$truckPriceType = '';
if (isset($truck['truckPriceType']) && isset($lang['TXT_70'][$truck['truckPriceType']])){
	$truckPriceType = ', '.$lang['TXT_70'][$truck['truckPriceType']];
}
$tmpl -> setValue('TRUCK_PRICE_TYPE', $truckPriceType);

//Set TRUCK_KM
$truckKMVal = $truck['truckKM'];
if (isset($lang['TXT_75'][$truck['truckKMType']])){
	$truckKMVal .= ' '.$lang['TXT_75'][$truck['truckKMType']];
}
$tmpl -> setValue('TRUCK_KM', $truckKMVal);

//Set TRUCK_POWER
$truckPower = '';
if (isset($truck['truckPowerType']) && isset($lang['TXT_72'][$truck['truckPowerType']])){
	if ($truck['truckPowerType'] == 0){
		$truckPower = $str2NumFilter -> filter(array('val' => $truck['truckPower'],
												'dec_place' => 0
												)
										).' '.$lang['TXT_72'][0]
					.' ('.$str2NumFilter -> filter(array('val' => ($truck['truckPower']*90/66),
												'dec_place' => 0
												)
										).' '.$lang['TXT_72'][1].')';
	}
	elseif ($truck['truckPowerType'] == 1){
		$truckPower = ($truck['truckPower']*66/90).' '.$lang['TXT_72'][0]
					.' ('.$truck['truckPower'].' '.$lang['TXT_72'][1].')';
	}
}
$tmpl -> setValue('TRUCK_POWER', $truckPower);
/*
$truckPower = '';
if (isset($truck['truckPowerType']) && isset($lang['TXT_72'][$truck['truckPowerType']])){
	if ($truck['truckPowerType'] == 0){
		$truckPower = $truck['truckPower'].' '.$lang['TXT_72'][0]
					.' ('.($truck['truckPower']*90/66).' '.$lang['TXT_72'][1].')';
	}
	elseif ($truck['truckPowerType'] == 1){
		$truckPower = ($truck['truckPower']*66/90).' '.$lang['TXT_72'][0]
					.' ('.$truck['truckPower'].' '.$lang['TXT_72'][1].')';
	}
}
$tmpl -> setValue('TRUCK_POWER', $truckPower);
*/

//Set TRUCK_EZ
$tmpl -> setValue('TRUCK_EZ', $truck['truckEZM'].'/'.$truck['truckEZY']);

//HSN
$truckHSN = $lang['TXT_40'];
if (isset($truck['truckHSN']) && ($truck['truckHSN'] != false)){
	$truckHSN = $truck['truckHSN'];
}
$tmpl -> setValue('TRUCK_HSN', $truckHSN);

//TSN
$truckTSN = $lang['TXT_40'];
if (isset($truck['truckTSN']) && ($truck['truckTSN'] != false)){
	$truckTSN = $truck['truckTSN'];
}
$tmpl -> setValue('TRUCK_TSN', $truckTSN);

//FIN
$truckFIN = $lang['TXT_40'];
if (isset($truck['truckFIN']) && ($truck['truckFIN'] != false)){
	$truckFIN = $truck['truckFIN'];
}
$tmpl -> setValue('TRUCK_FIN', $truckFIN);

//Set TRUCK_TUV
$truckTUV = $lang['TXT_40'];
if (isset($truck['truckTUVY']) && ($truck['truckTUVY'] != false) && ($truck['truckTUVY'] != -1)){
	$truckTUV = $truck['truckTUVY'];
	if (isset($truck['truckTUVM']) && ($truck['truckTUVM'] != false) && ($truck['truckTUVM'] != -1)){
		$truckTUV = $truck['truckTUVM'].'/'.$truckTUV;
	}
}
$tmpl -> setValue('TRUCK_TUV', $truckTUV);

//Set TRUCK_AU
$truckAU = $lang['TXT_40'];
if (isset($truck['truckAUY']) && ($truck['truckAUY'] != false) && ($truck['truckAUY'] != -1)){
	$truckAU = $truck['truckAUY'];
	if (isset($truck['truckAUM']) && ($truck['truckAUM'] != false) && ($truck['truckAUM'] != -1)){
		$truckAU = $truck['truckAUM'].'/'.$truckAU;
	}
}
$tmpl -> setValue('TRUCK_AU', $truckAU);

//Set TRUCK_SHIFT
$truckShift = $lang['TXT_40'];
if (isset($truck['truckShift']) && isset($lang['V_SHIFT'][$truck['truckShift']]) ){
	$truckShift = $lang['V_SHIFT'][$truck['truckShift']];
}
$tmpl -> setValue('TRUCK_SHIFT', $truckShift);

//Set TRUCK_WEIGHT
$truckWeight = $lang['TXT_40'];
if (isset($truck['truckWeight']) && ($truck['truckWeight'] != false)){
	$truckWeight = $truck['truckWeight'];
}
$tmpl -> setValue('TRUCK_WEIGHT', $truckWeight);

//Set TRUCK_CYL
$truckCyl = $lang['TXT_40'];
if (isset($truck['truckCyl']) && ($truck['truckCyl'] != false)){
	$truckCyl = $truck['truckCyl'];
}
$tmpl -> setValue('TRUCK_CYL', $truckCyl);

//Set TRUCK_CUB
$truckCub = $lang['TXT_40'];
if (isset($truck['truckCub']) && ($truck['truckCub'] != false)){
	$truckCub = $truck['truckCub'];
}
$tmpl -> setValue('TRUCK_CUB', $truckCub);

//Set TRUCK_USE_IN
$truckUseIn = $lang['TXT_40'];
if (isset($truck['truckUseIn']) && ($fCheckSpace -> filter($truck['truckUseIn']) == false)){
	$truckUseIn = $truck['truckUseIn'].' '.$lang['TXT_64'];
}
$tmpl -> setValue('TRUCK_USE_IN', $truckUseIn);

//Set TRUCK_USE_OUT
$truckUseOut = $lang['TXT_40'];
if (isset($truck['truckUseOut']) && ($fCheckSpace -> filter($truck['truckUseOut']) == false)){
	$truckUseOut = $truck['truckUseOut'].' '.$lang['TXT_64'];
}
$tmpl -> setValue('TRUCK_USE_OUT', $truckUseOut);

//Set TRUCK_CO2
$truckCO2 = $lang['TXT_40'];
if (isset($truck['truckCO2']) && ($fCheckSpace -> filter($truck['truckCO2']) == false)){
	$truckCO2 = $truck['truckCO2'].' '.$lang['TXT_66'];
}
$tmpl -> setValue('TRUCK_CO2', $truckCO2);

//Set TRUCK_STATE
$truckState = $lang['TXT_40'];
if (isset($truck['truckState']) && isset($lang['V_STATE'][$truck['truckState']]) ){
	$truckState = $lang['V_STATE'][$truck['truckState']];
}
$tmpl -> setValue('TRUCK_STATE', $truckState);

//Set TRUCK_CAT
$truckCatVal = $lang['TXT_40'];	
if (isset($this -> truck['truckCat']) && is_array($truckCat)){
	foreach($truckCat as $key => $kVal){
		if (($kVal['truckCatID'] == $this -> truck['truckCat']) && isset($lang['V_CAT'][$kVal['vcatID']])){
			$truckCatVal = $lang['V_CAT'][$kVal['vcatID']];
			break;
		}
	}
}
$tmpl -> setValue('TRUCK_CAT', $truckCatVal);
/*
$truckCat = '';
if (isset($truck['truckCat']) && isset($lang['TRUCK_CAT'][$truck['truckCat']]) ){
	$truckCat .= $lang['TRUCK_CAT'][$truck['truckCat']];
}
$tmpl -> setValue('TRUCK_CAT', $truckCat);
*/
//Set TRUCK_FUEL
$truckFuel = $lang['TXT_40'];
if (isset($truck['truckFuel']) && isset($lang['V_FUEL'][$truck['truckFuel']]) ){
	$truckFuel = $lang['V_FUEL'][$truck['truckFuel']];
}
$tmpl -> setValue('TRUCK_FUEL', $truckFuel);

//Set TRUCK_CLR
$truckClr = $lang['TXT_40'];
if (isset($truck['truckClr']) && isset($lang['V_CLR'][$truck['truckClr']]) ){
	$truckClr = $lang['V_CLR'][$truck['truckClr']];
	if (isset($truck['truckClrMet'])){
		$truckClr .= ' '.$lang['TXT_20'];
	}
}
$tmpl -> setValue('TRUCK_CLR', $truckClr);

//Set TRUCK_EMISSION_NORM
$truckEmissionNorm = $lang['TXT_40'];
if (isset($truck['truckEmissionNorm']) && isset($lang['V_EMISSION_NORM'][$truck['truckEmissionNorm']]) ){
	$truckEmissionNorm = $lang['V_EMISSION_NORM'][$truck['truckEmissionNorm']];
}
$tmpl -> setValue('TRUCK_EMISSION_NORM', $truckEmissionNorm);

//Set TRUCK_ECOLOGIC_TAG
$truckEcologicTag = $lang['TXT_40'];
if (isset($truck['truckEcologicTag']) && isset($lang['V_ECOLOGIC_TAG'][$truck['truckEcologicTag']]) ){
	$truckEcologicTag = $lang['V_ECOLOGIC_TAG'][$truck['truckEcologicTag']];
}
$tmpl -> setValue('TRUCK_ECOLOGIC_TAG', $truckEcologicTag);

//Set TRUCK_EXT
$truckExt = '';
if (isset($truck['truckExtDB']) && is_array($truck['truckExtDB'])){
	foreach ($truck['truckExtDB'] as $truckExtDB){
		$truckExt .= $lang['V_EXTRA'][$truckExtDB['vextID']].', ';
	}
}
if ($truckExt == ''){
	$truckExt = $lang['TXT_40'];
}
$tmpl -> setValue('TRUCK_EXTRA', $truckExt);

//Set TRUCK_KLIMA
$truckKlima = $lang['TXT_40'];
if (isset($truck['truckKlima']) && isset($lang['V_KLIMA'][$truck['truckKlima']]) ){
	$truckKlima = $lang['V_KLIMA'][$truck['truckKlima']];
}
$tmpl -> setValue('TRUCK_KLIMA', $truckKlima);

//Set TRUCK_DSC
$truckDesc = $lang['TXT_40'];
if (isset($truck['truckDesc']) && ($fCheckSpace -> filter($this -> truck['truckDesc']) == false)){
	$truckDesc = $truck['truckDesc'];
}
$tmpl -> setValue('TRUCK_DESC', $truckDesc);

//Set USER_ADS
$userAds = '';
if (isset($truck['userAds']) ){
	if($truck['userAds'] == 1){
		$userAds = $lang['TXT_33'][1];
	}
	else if($truck['userAds'] == 2){
		$userAds = $lang['TXT_33'][2];
	}
	else if($truck['userAds'] == 3){
		$userAds = $lang['TXT_33'][3];
	}
}
$tmpl -> setValue('USER_ADS', $userAds);

//Set USER_FIRM
$userFirm = $lang['TXT_40'];
if (isset($truck['userFirm']) && ($fCheckSpace -> filter($truck['userFirm']) == false)){
	$userFirm = $truck['userFirm'];
}
$tmpl -> setValue('USER_FIRM', $userFirm);

//Set USER_VNAME, USER_NNAME
$tmpl -> setValue('USER_NAME', $truck['userNName'].' '.$truck['userVName']);
//$tmpl -> setValue('USER_NNAME', $truck['userNName']);
//$tmpl -> setValue('USER_VNAME', $truck['userVName']);

//Set USER_EMAIL
$tmpl -> setValue('USER_EMAIL', $truck['userEMail']);

//Set USER_ADRESS
$userAddress = $lang['TXT_40'];
if (isset($truck['userAdress']) || isset($truck['userPLZ']) || isset($truck['userOrt'])){
	$userAddress = '';
	if (isset($truck['userAdress']) && ($fCheckSpace -> filter($truck['userAdress']) == false)){
		$userAddress .= '<li>'.$truck['userAdress'].'</li>';
	}
	if (isset($truck['userPLZ']) && isset($truck['userOrt'])
		 && ($fCheckSpace -> filter($truck['userPLZ']) == false)
		  && ($fCheckSpace -> filter($truck['userOrt']) == false)){
		$userAddress .= '<li>'.$truck['userPLZ'].' '.$truck['userOrt'].'</li>';
	}
	else if (isset($truck['userPLZ']) && ($fCheckSpace -> filter($truck['userPLZ']) == false)){
		$userAddress .= '<li>'.$truck['userPLZ'].'</li>';
	}
	else if (isset($truck['userOrt']) && ($fCheckSpace -> filter($truck['userOrt']) == false)){
		$userAddress .= '<li>'.$truck['userOrt'].'</li>';
	}
}
if ($userAddress != ''){
	//$userAddress = '	<li><span>'.$lang['TXT_54'].'</span><ul>'.$userAddress.'</ul></li>';
	$userAddress = '	<li><ul>'.$userAddress.'</ul></li>';
}
else{
	$userAddress = '';
}
$tmpl -> setValue('USER_ADDRESS', $userAddress);

//Set USER_TEL1
$userTel = $lang['TXT_40'];
if (isset($truck['userTel1']) && ($fCheckSpace -> filter($truck['userTel1']) == false)){
	//$userTel .= '<li><span>'.$lang['TXT_80'].'</span>'.$truck['userTel2'].'</li>';
	$userTel = $truck['userTel1'];
}
$tmpl -> setValue('USER_TEL1', $userTel);

//Set USER_TEL2
$userTel = $lang['TXT_40'];
if (isset($truck['userTel2']) && ($fCheckSpace -> filter($truck['userTel2']) == false)){
	$userTel = $truck['userTel2'];
}
$tmpl -> setValue('USER_TEL2', $userTel);

//Set truckLoc
$truckLoc = '';
if (isset($truck['truckLocPLZ']) && ($truck['truckLocPLZ'] != null)){
	if ($truckLoc != ''){
		$truckLoc .= ' ';
	}
	$truckLoc .= $truck['truckLocPLZ'];
}
if (isset($truck['truckLocOrt']) && ($truck['truckLocOrt'] != null)){
	if ($truckLoc != ''){
		$truckLoc .= ' ';
	}
	$truckLoc .= ' '.$truck['truckLocOrt'];
}
if (isset($truck['truckLocCountry']) && isset($lang['COUNTRY'][$truck['truckLocCountry']])){
	if ($truckLoc != ''){
		$truckLoc .= ', ';
	}
	$truckLoc .= ' '.$lang['COUNTRY'][$truck['truckLocCountry']];
}
$tmpl -> setValue('TRUCK_LOC', $truckLoc);



//Read gallery image pattern
$photoUploadEntryTMPL = $tmpl -> readFile('default/photoUploadEntry.html');
/*
 * Set TRUCK_PHOTO upload function
 * This depends on the activation of javascript
 */
//JS activated
/*
$truck['jsActive'] = true;
if (isset($truck['jsActive']) 
	&& ($truck['jsActive'] != null)
	&& ($truck['jsActive'] != false)){*/
//	Set javascript file for photo upload
	$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').'
									<script type="text/javascript" src="'.System_Properties::JS_PATH.'/carouFredSel_4_4_1.js"></script>
									<script type="text/javascript" src="'.System_Properties::JS_PATH.'/prettyPhoto.js"></script>
									<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/ajaxupload.js"></script>	
									<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/ti.js"></script>');
			
	
	//$photoUploadEntryTMPL = $tmpl -> readFile('default/photoUploadEntry_JSON.html');
	
	$gl_galIMGPattern = $tmpl -> replace(	'IMG_SRC',
											'p1',
											$photoUploadEntryTMPL
										);
	$gl_galIMGPattern = $tmpl -> replace(	'IMG_ID',
											'p2',
											$gl_galIMGPattern
										);		
	$gl_galIMGPattern = $tmpl -> replace(	'IMG_HREF',
											'',
											$gl_galIMGPattern
										);		
									
	//Read gallery template for activated javascript
	$tmpl -> readTMPLFile('TRUCK_PHOTO_GALLERY','default/photoGalleryJSON.html');
		
	//Set javascript gallery image pattern																
	$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
								.'	g_arr["GAL_IMG_PAT"] = \''.$gl_galIMGPattern.'\';'
					);//g_arr["TRUCK_ID"] = \''.$truck['truckID'].'\';
					
	$truckPhotos = '';
	if (isset($truck['truckPhoto']) && is_array($truck['truckPhoto'])){
		foreach ($truck['truckPhoto'] as $key => $truckPhoto){
			$imgSrc = System_Properties::PIC_PATH.'/'.System_Properties::TRUCK_ABRV.'_'.$truckPhoto['vID'].'_'.$truckPhoto['vPicID'].'.jpeg';
			
			if (file_exists('.'.$imgSrc)){
				$photoUploadEntry = $tmpl -> replace(	'IMG_SRC',
														$imgSrc,
														$photoUploadEntryTMPL
													);
				$photoUploadEntry = $tmpl -> replace(	'IMG_ID',
														$truckPhoto['vPicID'],
														$photoUploadEntry
													);
				$photoUploadEntry = $tmpl -> replace(	'IMG_HREF',
														'',
														$photoUploadEntry
													);
				$truckPhotos .= $photoUploadEntry;//'<div><a>X</a><img src="'.$truckPhoto.'" id="'.$key.'"/></div>';						
			}
		}
	}
	$tmpl -> setValue('PHOTO_GALLERY_ENTRIES', $truckPhotos);
	/*
}
//JS Deactivated
else{
	//Read gallery template for deactivated javascript
	$tmpl -> readTMPLFile('TRUCK_PHOTO_GALLERY','default/photoGalleryJSOFF.html');
	$tmpl -> setValue('TRUCK_ID', $truck['truckID']);
	
	$truckPhotos = '';
	if (isset($truck['truckPhoto']) && is_array($truck['truckPhoto'])){
		foreach ($truck['truckPhoto'] as $key => $truckPhoto){
			$imgSrc = System_Properties::PIC_PATH.'/'.$truckPhoto['vID'].'_'.$truckPhoto['vPicID'].'.jpeg';
			
			if (file_exists('.'.$imgSrc)){
				$photoUploadEntry = $tmpl -> replace(	'IMG_SRC',
														$imgSrc,
														$photoUploadEntryTMPL
													);
				$photoUploadEntry = $tmpl -> replace(	'IMG_ID',
														$truckPhoto['vPicID'],
														$photoUploadEntry
													);
				$photoUploadEntry = $tmpl -> replace(	'IMG_HREF',
														'href="'.System_Properties::ADMIN_MOD_PATH.'/truck/insert/dp/1/i/'.$truckPhoto['vPicID'].'"',
														$photoUploadEntry
													);
													
				$truckPhotos .= $photoUploadEntry;//'<div><a>X</a><img src="'.$truckPhoto.'" id="'.$key.'"/></div>';						
			}
		}
	}
	$tmpl -> setValue('PHOTO_GALLERY_ENTRIES', $truckPhotos);
}
*/
//INFO
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}

$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);	

echo $tmpl -> render();

?>

