<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for truck maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
include_once('default/views/helpers/func_pageCounter.phtml');
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/truck/truckQuickSearch.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$searchParam = $this -> searchParam;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/truck/search.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/truck.css" />');


												
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').'
								<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/ts.js"></script>');	

//process search results
$truckSearchResVal = '';
if (isset($this -> truckAds)
	&& is_array($this -> truckAds)
	&& (count($this -> truckAds) > 0) 
	){	
		//print_r($this -> truckAds);
	$truckSearchResVal .= '<table>';	
	foreach ($this -> truckAds['truckAds'] as $truck){
		$truckBrandNModel = $truck['truckBrandName'];
		if (isset($truck['truckModelName'])){
			$truckBrandNModel .= ' '.$truck['truckModelName'];
		}
		
		$truckSearchResVal .= '<tr>
							<td><a href="{-ADMIN_MOD_PATH-}/truck/detail/id/'.$truck['truckID'].'" title="'.$lang['TXT_122'].'">'.$truckBrandNModel.'</a></td>
							<td><a href="/truck/'.$truck['truckID'].'" target="blank">{-TXT_125-}</a></td>
							</tr>';
	}			
	$truckSearchResVal .= '</table>';
	$truckSearchResVal .= pageCounter($this -> truckAds['totalAds'], '{-ADMIN_MOD_PATH-}/truck/search/page/', $this -> truckAds['actPage'], $this -> truckAds['numAds']);
}else{
	$searchResVal = $lang['AERR_10'];
}
$tmpl -> setValue('TRUCK_SEARCH_RES_VAL', $truckSearchResVal);

//INFO
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}

$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $tmpl -> render();
?>
