<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for truck maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
//include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/truck/truckQuickSearch.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$truckExt = $this -> truckExt;
$cntTruck2Ext = $this -> cntTruck2Ext;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/truck/truckextraerase.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/truck.css" />
								<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');
	/*							
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', '	<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/jq_141_min.js"></script>
								<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/cs.js"></script>');	

*/

$tmpl -> setValue('TRUCK_EXTRA_CONFIRM_TEXT', $lang['ATXT_115']);

//TRUCK_EXTRA_ID
$tmpl -> setValue('TRUCK_EXTRA_ID', $truckExt['truckExtID']);

//NUM_SUB_EXT
$numTruckExt = 0;
if (is_array($truckExt) && isset($truckExt['children'])){
	$numTruckExt = $truckExt['children'];
}
$tmpl -> setValue('NUM_SUB_EXT', $numTruckExt);

//NUM_TRUCK_ADS
$numTruck2Ext = 0;
if (is_array($cntTruck2Ext) && isset($cntTruck2Ext['count_num'])){
	$numTruck2Ext = $cntTruck2Ext['count_num'];
}
$tmpl -> setValue('NUM_TRUCK_ADS', $numTruck2Ext);


//TRUCK_EXT_NAME
$truckExtName = '';
if (isset($truckExt['vextID']) && isset($lang['V_EXTRA'][$truckExt['vextID']])){
	$truckExtName = $lang['V_EXTRA'][$truckExt['vextID']];
}
$tmpl -> setValue('TRUCK_EXT_NAME', $truckExtName);


//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $tmpl -> render();
?>
