<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view handles the UI for truck maintenance
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$truckVcat = $this -> truckVcat;
$truckVcatParent = $this -> truckVcatParent;
$truckVcatAll = $this -> truckVcatAll;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/truck/truckcatedit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/truckd.css" />
								<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');
/*							
//Set javascript gallery image pattern																
$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
							.'	var g_arr = new Array();
								g_arr["ADMIN_MOD_PATH"] = "'.System_Properties::ADMIN_MOD_PATH.'";'
				);
				
$tmpl -> setValue('JS_FILES', '	<script type="tcat/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/jq_141_min.js"></script>
								<script type="tcat/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/cs.js"></script>');	

*/
//set V_CAT new
if (isset($lang['V_CAT'][$truckVcat['vcatID']])){
	$tmpl -> setValue('V_CAT_NEW', $lang['V_CAT'][$truckVcat['vcatID']]);
	$tmpl -> setValue('TRUCK_CAT_ID', $truckVcat['truckCatID']);
}

//set V_CAT_PARENT
//process vcat parent list and truck cat list
$vcatParent = '<select name="vcatParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($truckVcatAll)){
	foreach($truckVcatAll as $key => $vpValue){
		if (isset($lang['V_CAT'][$vpValue['vcatID']])){
			$vcatParent .= '<option value="'.$vpValue['truckCatID'].'" class="level'.$vpValue['level'].'"';
			if(isset($truckVcatParent['truckCatID']) && ($truckVcatParent['truckCatID'] == $vpValue['truckCatID'])){
				$vcatParent .= ' selected ';
			}
			$vcatParent .= '>'.$lang['V_CAT'][$vpValue['vcatID']].'</option>';
		}
	}
}
$vcatParent .= '</select>';
$tmpl -> setValue('V_CAT_PARENT', $vcatParent);


//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $tmpl -> render();
?>
