<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$brand = $this -> brand;
$bikeModelParent = $this -> bikeModelParent;
$bikeBrand = $this -> bikeBrand;
$bikeModel = $this -> bikeModel;
$allBikeModel = $this -> allBikeModel;
$delBikeAds = $this -> delBikeAds;
$delModelChild = $this -> delModelChild;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/bikebrandmodeledit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');															

//BIKE_BRAND_MODEL_VAL
$tmpl -> setValue('BIKE_BRAND_MODEL_VAL', $bikeModel['bikeModelName']);

//BRAND_NAME_VAL
$brandNameVal = '';
if (isset($bikeBrand) && is_array($bikeBrand)){
	$brandNameVal .= $bikeBrand['brandName'];
}
//MODEL_ID_VAL
$modelIDVal = '';
if (isset($bikeModel) && is_array($bikeModel)){
	$modelIDVal = $bikeModel['bikeModelID'];
}
$tmpl -> setValue('BRAND_NAME_VAL', $brandNameVal);
$tmpl -> setValue('MODEL_ID_VAL', $modelIDVal);

//BIKE_BRAND_MODEL
$bikeBrandModel = '<select name="brandModelParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';

//BIKE_MODEL_NAME_VAL
$bikeModelNameVal = '<select name="mid">';
if (isset($allBikeModel) && is_array($allBikeModel)){	
	foreach ($allBikeModel as $cm){
		//BIKE_BRAND_MODEL
		$bikeBrandModel .= '<option value="'.$cm['bikeModelID'].'"  style="padding-left:'.($cm['level'] * 5).'px;" class="'.$cm['level'].'"';
		if (is_array($bikeModelParent) 
			&& isset($bikeModelParent['bikeModelID']) 
			&& ($bikeModelParent['bikeModelID'] == $cm['bikeModelID'])){
			$bikeBrandModel .= ' selected ';
		}
		$bikeBrandModel .= '>'.$cm['bikeModelName'].'</option>';
		
		//BIKE_MODEL_NAME_VAL
		$bikeModelNameVal .= '<option value="'.$cm['bikeModelID'].'" style="padding-left:'.($cm['level'] * 5).'px;"  ';
		if ($cm['bikeModelID'] == $bikeModel['bikeModelID']){
			$bikeModelNameVal .= ' selected ';
		}
		$bikeModelNameVal .= '>'.$cm['bikeModelName'].'</option>';
	}
}
//BIKE_BRAND_MODEL
$bikeBrandModel .= '</select>';
$tmpl -> setValue('BIKE_BRAND_MODEL', $bikeBrandModel);

//BIKE_MODEL_NAME_VAL
$bikeModelNameVal .= '</select>';
$tmpl -> setValue('BIKE_MODEL_NAME_VAL', $bikeModelNameVal);

//DEL_BIKE_ADS_VAL
if (is_array($delBikeAds)){
	if(!isset($delBikeAds['totalRows'])){
		$delBikeAds['totalRows'] = count($delBikeAds);
	}
	
	$delBikeAdsVal = '<br/><br/>'.$lang['ATXT_67'].'<br/><input type="submit" name="modelDel2" value="'.$lang['ATXT_56'].'"/>';
	
	//MODEL_CHILD
	$delModelChildVal = '';
	if (is_array($delModelChild) && (count($delModelChild) > 0)){
		$delModelChildVal = '<ul>';
		foreach ($delModelChild as $modChild){
			$delModelChildVal .= '<li>'.$modChild['bikeModelName'].'</li>';
		}
		$delModelChildVal .= '</ul>';		
	}else{
		$delModelChildVal = '---';
	}
	
	$tmpl -> setValue('MODEL_NAME', $bikeModel['bikeModelName']);
	$tmpl -> setValue('MODEL_ADS_NUM', $delBikeAds['totalRows']);
	$tmpl -> setValue('MODEL_CHILD', $delModelChildVal);
}else{
	$delBikeAdsVal = '<input type="submit" name="modelDel" value="'.$lang['ATXT_56'].'"/>';
}

$tmpl -> setValue('DEL_BIKE_ADS_VAL' ,$delBikeAdsVal);


//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();
?>
