<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/system/brandmodelform.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$brand = $this -> brand;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/brandmodelnew.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');															


//BRAND_NAME_VAL, BRAND_ID_VAL
$brandNameVal = '';
$brandIDVal = '';
if (isset($brand) && is_array($brand)){
	$brandNameVal .= $brand['brandName'];
	$brandIDVal = $brand['brandID'];
}
$tmpl -> setValue('BRAND_NAME_VAL', $brandNameVal);
$tmpl -> setValue('BRAND_ID_VAL', $brandIDVal);


//INFO
$info = '';
if (isset($this -> error)){
	$info = $this -> error;
}
if (isset($this -> info)){
	$info = $this -> info;
}
$tmpl -> setValue('INFO', $info);

echo $this -> tmpl -> render();
?>
