<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$brand = $this -> brand;
$brandModelParent = $this -> brandModelParent;
$carBrand = $this -> carBrand;
$carModel = $this -> carModel;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/carbrandmodel.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');															

//SUBMIT_BTN
$tmpl -> setValue('SUBMIT_BTN', '');

//BRAND_NAME_VAL, BRAND_ID_VAL
$brandNameVal = '';
$brandIDVal = '';
if (isset($brand) && is_array($brand)){
	$brandNameVal .= $brand['brandName'];
	$brandIDVal = $brand['brandID'];
}
$tmpl -> setValue('BRAND_NAME_VAL', $brandNameVal);
$tmpl -> setValue('BRAND_ID_VAL', $brandIDVal);

$carBrandNameVal = '<select name="bid">';
if (isset($carBrand) && is_array($carBrand)){
	foreach ($carBrand as $cb){
		$carBrandNameVal .= '<option value="'.$cb['brandID'].'"';
		if ($cb['brandID'] == $brand['brandID']){
			$carBrandNameVal .= ' selected ';
		}
		$carBrandNameVal .= '>'.$cb['brandName'].'</option>';
	}
}
$carBrandNameVal .= '</select>';
$tmpl -> setValue('CAR_BRAND_NAME_VAL', $carBrandNameVal);

//CAR_BRAND_MODEL_VAL
$carBrandModel = '<select name="brandModelParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';
$carBrandModelVal = '';
if (isset($carModel) && is_array($carModel)){
	foreach ($carModel as $cm){
		$carBrandModel .= '<option value="'.$cm['carModelID'].'" class="level'.$cm['level'].'"';
		if (isset($brandModelParent) && ($brandModelParent == $cm['carModelID'])){
			$carBrandModel .= ' selected ';
		}
		$carBrandModel .= '>'.$cm['carModelName'].'</option>';
		$carBrandModelVal .= '<tr>
								<td><a href="{-ADMIN_MOD_PATH-}/system/carbrandmodeledit/mid/'.$cm['carModelID'].'">'.$lang['TXT_144'].'</a></td>
								<td class="level'.$cm['level'].'">'.$cm['carModelName'].'</td>								
								</tr>';
	}
}
$carBrandModel .= '</select>';
$tmpl -> setValue('CAR_BRAND_MODEL', $carBrandModel);
//$carBrandModelVal .= '</ul>';
$tmpl -> setValue('CAR_BRAND_MODEL_VAL', $carBrandModelVal);

//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);


echo $this -> tmpl -> render();
?>
