<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$brand = $this -> brand;
$carModelParent = $this -> carModelParent;
$carBrand = $this -> carBrand;
$carModel = $this -> carModel;
$allCarModel = $this -> allCarModel;
$delCarAds = $this -> delCarAds;
$delModelChild = $this -> delModelChild;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/carbrandmodeledit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');															

//CAR_BRAND_MODEL_VAL
$tmpl -> setValue('CAR_BRAND_MODEL_VAL', $carModel['carModelName']);

//BRAND_NAME_VAL
$brandNameVal = '';
if (isset($carBrand) && is_array($carBrand)){
	$brandNameVal .= $carBrand['brandName'];
}
//MODEL_ID_VAL
$modelIDVal = '';
if (isset($carModel) && is_array($carModel)){
	$modelIDVal = $carModel['carModelID'];
}
$tmpl -> setValue('BRAND_NAME_VAL', $brandNameVal);
$tmpl -> setValue('MODEL_ID_VAL', $modelIDVal);

//CAR_BRAND_MODEL
$carBrandModel = '<select name="brandModelParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';

//CAR_MODEL_NAME_VAL
$carModelNameVal = '<select name="mid">';
if (isset($allCarModel) && is_array($allCarModel)){	
	foreach ($allCarModel as $cm){
		//CAR_BRAND_MODEL
		$carBrandModel .= '<option value="'.$cm['carModelID'].'"  style="padding-left:'.($cm['level'] * 5).'px;" class="'.$cm['level'].'"';
		if (is_array($carModelParent) 
			&& isset($carModelParent['carModelID']) 
			&& ($carModelParent['carModelID'] == $cm['carModelID'])){
			$carBrandModel .= ' selected ';
		}
		$carBrandModel .= '>'.$cm['carModelName'].'</option>';
		
		//CAR_MODEL_NAME_VAL
		$carModelNameVal .= '<option value="'.$cm['carModelID'].'" style="padding-left:'.($cm['level'] * 5).'px;"  ';
		if ($cm['carModelID'] == $carModel['carModelID']){
			$carModelNameVal .= ' selected ';
		}
		$carModelNameVal .= '>'.$cm['carModelName'].'</option>';
	}
}
//CAR_BRAND_MODEL
$carBrandModel .= '</select>';
$tmpl -> setValue('CAR_BRAND_MODEL', $carBrandModel);

//CAR_MODEL_NAME_VAL
$carModelNameVal .= '</select>';
$tmpl -> setValue('CAR_MODEL_NAME_VAL', $carModelNameVal);

//DEL_CAR_ADS_VAL
if (is_array($delCarAds)){
	if(!isset($delCarAds['totalRows'])){
		$delCarAds['totalRows'] = count($delCarAds);
	}
	
	$delCarAdsVal = '<br/><br/>'.$lang['ATXT_67'].'<br/><input type="submit" name="modelDel2" value="'.$lang['ATXT_56'].'"/>';
	
	//MODEL_CHILD
	$delModelChildVal = '';
	if (is_array($delModelChild) && (count($delModelChild) > 0)){
		$delModelChildVal = '<ul>';
		foreach ($delModelChild as $modChild){
			$delModelChildVal .= '<li>'.$modChild['carModelName'].'</li>';
		}
		$delModelChildVal .= '</ul>';		
	}else{
		$delModelChildVal = '---';
	}
	
	$tmpl -> setValue('MODEL_NAME', $carModel['carModelName']);
	$tmpl -> setValue('MODEL_ADS_NUM', $delCarAds['totalRows']);
	$tmpl -> setValue('MODEL_CHILD', $delModelChildVal);
}else{
	$delCarAdsVal = '<input type="submit" name="modelDel" value="'.$lang['ATXT_56'].'"/>';
}
$tmpl -> setValue('DEL_CAR_ADS_VAL' ,$delCarAdsVal);

//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();
?>
