<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI for managing vehicle extras
 *********************************************************************************/
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/system/vextformnew.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$sysSystem = $this -> sysSystem;
$vext = $this -> vext;
$carExt = $this -> carExt;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/vext.html');

$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').'
								<script type="text/javascript" src="'.System_Properties::ADMIN_JS_PATH.'/vext.js"></script>');	

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');
								
$vextVal = '';
if (is_array($vext)){
	$vextVal = '<table>
				<tr>
					<th>'.$lang['TXT_83'].'</th>
					<th>'.$lang['ATXT_50'].'</th>
					<th>'.$lang['ATXT_51'].'</th>
					<th>'.$lang['ATXT_52'].'</th>
				</tr>';
	foreach ($vext as $v){
		if (isset($lang['V_EXTRA'][$v['vextID']])){
			$vextVal .= '<tr>
							<td>'.$lang['V_EXTRA'][$v['vextID']].'</td>
							<td><input type="checkbox" disabled ';
			if (isset($v['carExtExist']) && ($v['carExtExist'] == 1)){
				$vextVal .= ' checked ';
			}
			$vextVal .= '/></td>
							<td><input type="checkbox" disabled ';
			if (isset($v['bikeExtExist']) && ($v['bikeExtExist'] == 1)){
				$vextVal .= ' checked ';
			}
			$vextVal .= '/></td>
							<td><input type="checkbox" disabled ';
			if (isset($v['truckExtExist']) && ($v['truckExtExist'] == 1)){
				$vextVal .= ' checked ';
			}
			$vextVal .= '/></td>
						</tr>';
			/*
						<td>
							<a href="{-ADMIN_MOD_PATH-}/system/vextedit/vid/'.$v['vextID'].'">'.$lang['TXT_144'].'</a>
						</td>*/
		}
	}
	$vextVal .= '</table>';
}
$tmpl -> setValue('VEXT_VAL', $vextVal);
								
//INFO
$info = '';
if (isset($this -> error)){
	$info = $this -> error;
}
if (isset($this -> info)){
	$info = $this -> info;
}
$tmpl -> setValue('INFO', $info);

echo $this -> tmpl -> render();
?>
