<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$brand = $this -> brand;
$brandModelParent = $this -> brandModelParent;
$truckBrand = $this -> truckBrand;
$truckModel = $this -> truckModel;

$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/truckbrandmodel.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');															

//SUBMIT_BTN
$tmpl -> setValue('SUBMIT_BTN', '');

//BRAND_NAME_VAL, BRAND_ID_VAL
$brandNameVal = '';
$brandIDVal = '';
if (isset($brand) && is_array($brand)){
	$brandNameVal .= $brand['brandName'];
	$brandIDVal = $brand['brandID'];
}
$tmpl -> setValue('BRAND_NAME_VAL', $brandNameVal);
$tmpl -> setValue('BRAND_ID_VAL', $brandIDVal);

$truckBrandNameVal = '<select name="bid">';
if (isset($truckBrand) && is_array($truckBrand)){
	foreach ($truckBrand as $cb){
		$truckBrandNameVal .= '<option value="'.$cb['brandID'].'"';
		if ($cb['brandID'] == $brand['brandID']){
			$truckBrandNameVal .= ' selected ';
		}
		$truckBrandNameVal .= '>'.$cb['brandName'].'</option>';
	}
}
$truckBrandNameVal .= '</select>';
$tmpl -> setValue('TRUCK_BRAND_NAME_VAL', $truckBrandNameVal);

//TRUCK_BRAND_MODEL_VAL
$truckBrandModel = '<select name="brandModelParent">
					<option value="-1">'.$lang['ATXT_63'].'</option>';
$truckBrandModelVal = '';
if (isset($truckModel) && is_array($truckModel)){
	foreach ($truckModel as $cm){
		$truckBrandModel .= '<option value="'.$cm['truckModelID'].'" class="level'.$cm['level'].'"';
		if (isset($brandModelParent) && ($brandModelParent == $cm['truckModelID'])){
			$truckBrandModel .= ' selected ';
		}
		$truckBrandModel .= '>'.$cm['truckModelName'].'</option>';
		$truckBrandModelVal .= '<tr>
								<td><a href="{-ADMIN_MOD_PATH-}/system/truckbrandmodeledit/mid/'.$cm['truckModelID'].'">'.$lang['TXT_144'].'</a></td>
								<td class="level'.$cm['level'].'">'.$cm['truckModelName'].'</td>
								</tr>';
	}
}
$truckBrandModel .= '</select>';
$tmpl -> setValue('TRUCK_BRAND_MODEL', $truckBrandModel);
//$truckBrandModelVal .= '</ul>';
$tmpl -> setValue('TRUCK_BRAND_MODEL_VAL', $truckBrandModelVal);

								
//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();
?>
