<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI for managing vehicle categories
 *********************************************************************************/
include_once(System_Properties::ADMIN_MOD_PATH.'/views/scripts/system/vcatformedit.phtml');
$tmpl = $this -> tmpl;
$lang = $this -> lang;
$posLang = $this -> posLang;
$sysSystem = $this -> sysSystem;
$vcat = $this -> vcat;
$tmpl -> readTmplFile('CONTENT', System_Properties::ADMIN_MOD_PATH.'/system/vcatedit.html');

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::ADMIN_CSS_PATH.'/system.css" />');

$tmpl -> setValue('VCAT_ID', $vcat['vcatID']);
								
foreach ($posLang as $key => $value){
	$vcatName = '';
	if (isset($lang['V_CAT_'.strtoupper($value['langAbrv'])][$vcat['vcatID']])){
		$vcatName = $lang['V_CAT_'.strtoupper($value['langAbrv'])][$vcat['vcatID']];
	}
	$tmpl -> setValue('V_CAT_'.strtoupper($value['langAbrv']), $vcatName);
}
								
//Info
$infoVal = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $infoVal .= $error['RETURN'] : $error = '';
}

if (isset($this -> info)){
	$info = $tmpl -> tagMsg(array('INFO_MSG' => $this -> info));
	isset($info['RETURN']) ? $infoVal .= $info['RETURN'] : $error = '';
}
$tmpl -> setValue('INFO', $tmpl -> getValue('INFO').$infoVal);

echo $this -> tmpl -> render();
?>
