<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20101212
 * Desc:		This view describe the UI if a user is not logged in
 *********************************************************************************/
$tmpl = $this -> tmpl;
$lang = $this -> lang;

$posLang = $this -> posLang;

$vcatParam = $this -> vcatParam;

$tmpl -> readTmplFile('VCAT_FORM', System_Properties::ADMIN_MOD_PATH.'/system/vextform.html');
$tmpl -> setValue('SUBMIT_BTN', '<input type="submit" name="vcatNew" value="'.$lang['TXT_156'].'"/>');
$tmpl -> setValue('FORM_URL', '/'.System_Properties::ADMIN_MOD_PATH.'/system/vcat');

$tmpl -> setValue('VCAT_ID', '');

//Lang Header
$langHeader = '';
$langTxtField = '';
if (is_array($posLang)){
	foreach ($posLang as $key => $value){
		$langHeader .= '<td>'.$value['langAbrv'].'</td>';
		$langTxtField .= '<td><input type="text" name="lang_'.strtolower($value['langAbrv']).'" value="{-V_CAT_'.strtoupper($value['langAbrv']).'-}"/></td>';
	}
}
$tmpl -> setValue('LANG_HEADER', $langHeader);
$tmpl -> setValue('LANG_TXT_FIELD', $langTxtField);

/*
//CAR_BRAND_ACTIVE_CHECKED
$carBrandActiveChecked = '';
if (is_array($vcatParam) && isset($vcatParam['carActive']) && ($vcatParam['carActive'] == 1)){
	$carBrandActiveChecked .= 'checked';
}
$tmpl -> setValue('CAR_ACTIVE_CHECKED', $carBrandActiveChecked);

//BIKE_BRAND_ACTIVE_CHECKED
$bikeBrandActiveChecked = '';
if (is_array($vcatParam) && isset($vcatParam['bikeActive']) && ($vcatParam['bikeActive'] == 1)){
	$bikeBrandActiveChecked .= 'checked';
}
$tmpl -> setValue('BIKE_ACTIVE_CHECKED', $bikeBrandActiveChecked);

//TRUCK_BRAND_ACTIVE_CHECKED
$truckBrandActiveChecked = '';
if (is_array($vcatParam) && isset($vcatParam['truckActive']) && ($vcatParam['truckActive'] == 1)){
	$truckBrandActiveChecked .= 'checked';
}
$tmpl -> setValue('TRUCK_ACTIVE_CHECKED', $truckBrandActiveChecked);


//VCAT_NAME_VAL
$vcatNameVal = '';
if (is_array($vcatParam) && isset($vcatParam['vcatName'])){
	$vcatNameVal .= $vcatParam['vcatName'];
}
$tmpl -> setValue('VCAT_NAME_VAL', $vcatNameVal);

$tmpl -> setValue('VCAT_ID','');



//CAR_EXT_PARENT
$carExtParentVal = '<select name="carExtParent" disabled>
					<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($carExt)){
	foreach($carExt as $ce){
		if (isset($lang['V_CAT'][$ce['vcatID']])){
			$carExtParentVal .= '<option value="'.$ce['carExtID'].'">'.$lang['V_CAT'][$ce['vcatID']].'</option>';
		}else{
			$carExtParentVal .= '<option value="'.$ce['carExtID'].'">'.$ce['carExtID'].'</option>';
		}
	}
}
$carExtParentVal .= '</select>';
$tmpl -> setValue('CAR_EXT_PARENT', $carExtParentVal);

//BIKE_EXT_PARENT
$bikeExtParentVal = '<select name="bikeExtParent" disabled>
						<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($bikeExt)){
	foreach($bikeExt as $be){
		if (isset($lang['V_CAT'][$be['vcatID']])){
			$bikeExtParentVal .= '<option value="'.$be['bikeExtID'].'">'.$lang['V_CAT'][$be['vcatID']].'</option>';
		}else{
			$bikeExtParentVal .= '<option value="'.$be['bikeExtID'].'">'.$be['bikeExtID'].'</option>';
		}
	}
}
$bikeExtParentVal .= '</select>';
$tmpl -> setValue('BIKE_EXT_PARENT', $bikeExtParentVal);

//TRUCK_EXT_PARENT
$truckExtParentVal = '<select name="truckExtParent" disabled>
					<option value="-1">'.$lang['ATXT_63'].'</option>';
if (is_array($truckExt)){
	foreach($truckExt as $te){
		if (isset($lang['V_CAT'][$te['vcatID']])){
			$truckExtParentVal .= '<option value="'.$te['truckExtID'].'">'.$lang['V_CAT'][$te['vcatID']].'</option>';
		}else{
			$truckExtParentVal .= '<option value="'.$te['truckExtID'].'">'.$te['truckExtID'].'</option>';
		}
	}
}
$truckExtParentVal .= '</select>';
$tmpl -> setValue('TRUCK_EXT_PARENT', $truckExtParentVal);

//POS_LANG_VAL
$posLangVal = '<select name="lang">';
if (is_array($posLang)){	
	foreach ($posLang as $pl){
		$posLangVal .= '<option value="'.$pl['langID'].'">'.$pl['langAbrv'].'</option>';
	}
}
$posLangVal .= '</select>';
$tmpl -> setValue('POS_LANG_VAL', $posLangVal);
*/

?>