<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100906
 * Desc:		This is the view of PKW details
 *********************************************************************************/
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$lang = $this -> lang;
$truck = $this -> truck;
$truckCat = $this -> truckCat;

$str2NumFilter = new FormatSt2Num();
$strIsEmptyFilter = new FilterIsEmptyString();

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/truck_detail.css" />');
				
$tmpl -> readTmplFile('CONTENT', 'default/truck/detail.html');

//Set TRUCK_BRAND TRUCK_MODEL
$tmpl -> setValue('TRUCK_BRAND_VAL', $truck['truckBrandName']);
$truckModel = '';
if (isset($truck['truckModelName']) && ($truck['truckModelName'] != null)){
	$truckModel = $truck['truckModelName'];
}
$tmpl -> setValue('TRUCK_MODEL_VAL', $truckModel);

//Set TRUCK_PRICE
$truckPriceVal = $str2NumFilter -> filter(array('val' => $truck['truckPrice'],
																'dec_place' => 2
																)
														);
if (isset($lang['TXT_74'][$truck['truckPriceCurr']])){
	$truckPriceVal .= ' '.$lang['TXT_74'][$truck['truckPriceCurr']];
}														
$tmpl -> setValue('TRUCK_PRICE_VAL', $truckPriceVal);

$truckPriceType = '';
if (isset($lang['TXT_70'][$truck['truckPriceType']])){
	$truckPriceType = $lang['TXT_70'][$truck['truckPriceType']];
}
$tmpl -> setValue('TRUCK_PRICE_TYPE_VAL', $truckPriceType);

//Set TRUCK_KM
$truckKMVal = $str2NumFilter -> filter($truck['truckKM']);
if (isset($lang['TXT_75'][$truck['truckKMType']])){
	$truckKMVal .= ' '.$lang['TXT_75'][$truck['truckKMType']];
}
$tmpl -> setValue('TRUCK_KM_VAL', $truckKMVal);

//Set TRUCK_POWER
$truckPower = '';
//KW?
if ($truck['truckPowerType'] == 0){
	$truckPower = $str2NumFilter -> filter(array('val' => $truck['truckPower'],
												'dec_place' => 0
												)
										).$lang['TXT_72'][0].' ('.
				$str2NumFilter -> filter(array('val' => ($truck['truckPower']*90/66),
												'dec_place' => 0
												)
										).$lang['TXT_72'][1].')';
}
//PS?
else if($truck['truckPowerType'] == 1){
	$truckPower = $str2NumFilter -> filter(array('val' => ($truck['truckPower'] * 66/90),
												'dec_place' => 0
												)
										).$lang['TXT_72'][0].' ('.
				$str2NumFilter -> filter(array('val' => $truck['truckPower'],
												'dec_place' => 0
												)
										).$lang['TXT_72'][1].')';	
}
$tmpl -> setValue('TRUCK_POWER_VAL', $truckPower);

//Set TRUCK_EZ
$tmpl -> setValue('TRUCK_EZ', $truck['truckEZM'].'/'.$truck['truckEZY']);



//Set TRUCK_OPTIONAL_SPEC
$truckOpt = '';
//Add truckKlima
if (isset($lang['V_KLIMA'][$truck['truckKlima']])){
	$truckOpt .= '<li><span>'.$lang['TXT_109'].'</span> '.$lang['V_KLIMA'][$truck['truckKlima']].'</li>';
}
//Add truckCat
if (isset($truck['truckCat']) && ($truck['truckCat'] != -1) && is_array($truckCat)){
	foreach ($truckCat as $key => $kVal){
		if (($kVal['truckCatID'] == $truck['truckCat']) && isset($lang['V_CAT'][$kVal['vcatID']])){		
			$truckOpt .= '<li><span>'.$lang['TXT_18'].'</span> '.$lang['V_CAT'][$kVal['vcatID']].'</li>';
		}
	}
}
/*
$truckCatVal = '';	
if (isset($this -> truck['truckCat']) && is_array($truckCat)){
	foreach($truckCat as $key => $kVal){
		if (($kVal['truckCatID'] == $this -> truck['truckCat']) && isset($lang['V_CAT'][$kVal['vcatID']])){
			$truckCatVal .= $lang['V_CAT'][$kVal['vcatID']];
			break;
		}
	}
}
$tmpl -> setValue('TRUCK_CAT_VAL', $truckCatVal);
*/


//Add truckFuel
if (isset($lang['V_FUEL'][$truck['truckFuel']])){
	$truckOpt .= '<li><span>'.$lang['TXT_15'].'</span> '.$lang['V_FUEL'][$truck['truckFuel']].'</li>';
}
//Add truckClr
if (isset($lang['V_CLR'][$truck['truckClr']])){
	$truckOpt .= '<li><span>'.$lang['TXT_19'].'</span> '.$lang['V_CLR'][$truck['truckClr']];
	if (isset($truck['truckClrMet'])){
		$truckOpt .= ' '.$lang['TXT_20'];
	}
	$truckOpt .= '</li>';
}
//Add truckTUV
if (isset($truck['truckTUVY']) && ($truck['truckTUVY'] > 0)){
	$truckOpt .= '<li><span>'.$lang['TXT_76'].'</span>';
	if (isset($truck['truckTUVM']) && ($truck['truckTUVM'] > 0)){
		$truckOpt .= $truck['truckTUVM'].'/';
	}
	$truckOpt .= $truck['truckTUVY'].'</li>';
}
//Add truckAUV
if (isset($truck['truckAUY']) && ($truck['truckAUY'] > 0)){
	$truckOpt .= '<li><span>'.$lang['TXT_77'].'</span>';
	if (isset($truck['truckAUM']) && ($truck['truckAUM'] > 0)){
		$truckOpt .= $truck['truckAUM'].'/';
	}
	$truckOpt .= $truck['truckAUY'].'</li>';
}
//Add truckEcologicTag
if (isset($lang['V_ECOLOGIC_TAG'][$truck['truckEcologicTag']])){
	$truckOpt .= '<li><span>'.$lang['TXT_85'].'</span> '.$lang['V_ECOLOGIC_TAG'][$truck['truckEcologicTag']].'</li>';
}
//Add truckEmissionNorm
if (isset($lang['V_EMISSION_NORM'][$truck['truckEmissionNorm']])){
	$truckOpt .= '<li><span>'.$lang['TXT_22'].'</span> '.$lang['V_EMISSION_NORM'][$truck['truckEmissionNorm']].'</li>';
}
//Add truckCO2
if (isset($truck['truckCO2']) && ($truck['truckCO2'] != null)){
	$truckOpt .= '<li><span>'.$lang['TXT_65'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckCO2'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_66'].'</li>';
}
//Add truckUseIn
if (isset($truck['truckUseIn']) && ($truck['truckUseIn'] != null)){
	$truckOpt .= '<li><span>'.$lang['TXT_62'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckUseIn'],
																			'dec_place' => 1
																		)
																).'&nbsp;'.$lang['TXT_64'].'</li>';
}
//Add truckUseOut
if (isset($truck['truckUseOut']) && ($truck['truckUseOut'] != null)){
	$truckOpt .= '<li><span>'.$lang['TXT_63'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckUseOut'],
																			'dec_place' => 1
																		)
																).'&nbsp;'.$lang['TXT_64'].'</li>';
}
//Add truckCub
if (isset($truck['truckCub']) && ($truck['truckCub'] > 0)){
	$truckOpt .= '<li><span>'.$lang['TXT_59'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckCub'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_60'].'</li>';
}
//Add truckShift
if (isset($lang['V_SHIFT'][$truck['truckShift']])){
	$truckOpt.= '<li><span>'.$lang['TXT_21'].'</span> '.$lang['V_SHIFT'][$truck['truckShift']].'</li>';
}
//Add truckWeight
if (isset($truck['truckWeight']) && ($truck['truckWeight'] > 0)){
	$truckOpt .= '<li><span>'.$lang['TXT_57'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckWeight'],
																			'dec_place' => 0
																		)
																).'&nbsp;'.$lang['TXT_67'].'</li>';
}
//Add truckCyl
if (isset($truck['truckCyl']) && ($truck['truckCyl'] > 0)){
	$truckOpt .= '<li><span>'.$lang['TXT_58'].'</span> '. $str2NumFilter -> filter(array(	'val' => $truck['truckCyl'],
																			'dec_place' => 0
																		)
																).'</li>';
}

//Add truckState
if (isset($lang['V_STATE'][$truck['truckState']])){
	$truckOpt .= '<li><span>'.$lang['TXT_17'].'</span> '.$lang['V_STATE'][$truck['truckState']].'</li>';
}
if ($truckOpt != null){
	$truckOpt = '<li><strong class="heading">'.$lang['TXT_84'].'</strong></li>'.$truckOpt;
}

$tmpl -> setValue('TRUCK_OPTIONAL_SPEC', $truckOpt);

//Add truckDesc
$truckDesc = '';
if (isset($truck['truckDesc']) && ($strIsEmptyFilter -> filter($truck['truckDesc']) == false)){
	$truckDesc = '<li><strong class="heading">'.$lang['TXT_68'].'</strong></li>
				<li class="justify">'.$truck['truckDesc'].'</li>';
}
$tmpl -> setValue('TRUCK_DESC', $truckDesc);

//Add truckExt
$truckExtStr = '';
if (isset($truck['truckExt']) && is_array($truck['truckExt']) && (count($truck['truckExt'])>0)){
	//$truckExtStr .= '<li>'.$lang['TXT_83'].'<br/>';
	$truckExtStr = '<li><strong class="heading">'.$lang['TXT_83'].'</strong></li>
				<li class="justify">';
	foreach ($truck['truckExt'] as $truckExt){
		if (isset($lang['V_EXTRA'][$truckExt['vextID']])){
			$truckExtStr .= $lang['V_EXTRA'][$truckExt['vextID']].', ';
		}
	}
	$truckExtStr .= '</li>';
}
$tmpl -> setValue('TRUCK_EXTRA', $truckExtStr);

//Set USER_ADS
$userAds = '';
if (isset($truck['userAds'])){
	switch ($truck['userAds']){
		case 1: $userAds = '&nbsp;('.$lang['TXT_33'][1].')';
				break;
		case 2: $userAds = '&nbsp;('.$lang['TXT_33'][2].')';
				break;
	}
}
$tmpl -> setValue('USER_ADS', $userAds);

//Set userFirm
$userFirm = '';
if (isset($truck['userFirm']) && ($truck['userFirm'] != null)){
	$userFirm .= '<li><span>'.$lang['TXT_53'].'</span>'.$truck['userFirm'].'</li>';
}
$tmpl -> setValue('USER_FIRM', $userFirm);

//Set userName
$userName = $truck['userNName'].' '.$truck['userVName'];
$tmpl -> setValue('USER_NAME', $userName);

//Set userAdress
$userAddress = '';
if (isset($truck['userAdress']) || isset($truck['userPLZ']) || isset($truck['userOrt'])){
	if (isset($truck['userAdress']) && ($strIsEmptyFilter -> filter($truck['userAdress']) == false)){
		$userAddress .= '<li>'.$truck['userAdress'].'</li>';
	}
	if (isset($truck['userPLZ']) && isset($truck['userOrt'])
		 && ($strIsEmptyFilter -> filter($truck['userPLZ']) == false)
		  && ($strIsEmptyFilter -> filter($truck['userOrt']) == false)){
		$userAddress .= '<li>'.$truck['userPLZ'].' '.$truck['userOrt'].'</li>';
	}
	else if (isset($truck['userPLZ']) && ($strIsEmptyFilter -> filter($truck['userPLZ']) == false)){
		$userAddress .= '<li>'.$truck['userPLZ'].'</li>';
	}
	else if (isset($truck['userOrt']) && ($strIsEmptyFilter -> filter($truck['userOrt']) == false)){
		$userAddress .= '<li>'.$truck['userOrt'].'</li>';
	}
}
if ($userAddress != ''){
	$userAddress = '	<li><span>'.$lang['TXT_54'].'</span>
						<ul>'.$userAddress.'</ul></li>';
}
else{
	$userAddress = '';
}
$tmpl -> setValue('USER_ADDRESS', $userAddress);


$truckLoc = '';	
if (isset($truck['truckLocPLZ']) && ($truck['truckLocPLZ'] != null)){
	$truckLoc = '	<li><strong class="heading">'.$lang['TXT_114'].'</strong></li>
				<li><div id="map"></div></li>';
	$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').
									'	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/map.js"></script>'
										);															
	$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
								.'	var $gl_mapLocPLZ = \''.$truck['truckLocPLZ'].'\';
									var $gl_mapLocCountry = \'DE\';'
					);
	
}
$tmpl -> setValue('TRUCK_LOC', $truckLoc);

//Set userTel
$userTel = '';
if (isset($truck['userTel1']) && ($strIsEmptyFilter -> filter($truck['userTel1']) == false)){
	$userTel .= '<li><span>'.$lang['TXT_80'].'</span>'.$truck['userTel1'].'</li>';
}
if (isset($truck['userTel2']) && ($strIsEmptyFilter -> filter($truck['userTel2']) == false)){
	$userTel .= '<li><span>'.$lang['TXT_80'].'</span>'.$truck['userTel2'].'</li>';
}
$tmpl -> setValue('USER_TEL', $userTel);


if (isset($truck['truckPics']) && is_array($truck['truckPics']) && (count($truck['truckPics']) > 0)){
	$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES').'
									<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/photo_gallery.css" />');
					$this -> truck['jsActive']  =true;
	if (isset($this -> truck['jsActive'])){ 
		$photoGallery = '<div id="photoGalleryCont"><ul id="photoGallery">';
		//Set photo gallery
		$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES')
										.'<script type="text/javascript" src="'.System_Properties::JS_PATH.'/js_active.js"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/truckouFredSel.js"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/prettyPhoto.js"></script>
										<script type="text/javascript" src="'.System_Properties::JS_PATH.'/photoGallery.js"></script>'
										);
		$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
										.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/prettyPhoto.css" />');
	
		//Set javascript gallery image pattern																
		$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
									.'var $gl_sysPicPath = \''.System_Properties::SYS_PIC_PATH.'\';'
						);
						
		foreach($truck['truckPics'] AS $truckPic){
			$photoGallery .= '	<li class="photo">
									<a rel="prettyPhoto[pp_gal]" href="/pic/'.System_Properties::TRUCK_ABRV.'_'.$truckPic['vID'].'_'.$truckPic['vPicID'].'.jpeg"><img src="/pic/'.System_Properties::TRUCK_ABRV.'_'.$truckPic['vID'].'_'.$truckPic['vPicID'].'.jpeg"/></a>
								</li>';
			//<a href="/truck/'.$truck['truckID'].'/'.$truck['page'].'/vp/'.$truckPic['vPicID'].'" target="_blank"><img src="/pic/'.$truckPic['vID'].'_'.$truckPic['vPicID'].'.jpeg"/></a>
		}
		$photoGallery .= '
						</ul>
						</div>
						<a id="prev" href="#">&lt;</a>
						<a id="next" href="#">&gt;</a>';				
	}
	else{	
		$photoGallery = '<div id="photoGalleryCont"><ul id="photoGallery">';
		
		$maxTruckPic = count($truck['truckPics']);
		
		if (isset($truck['next']) && ($truck['next'] != null)){
			$truck['lastPicPID']++;
		}
		else if (isset($truck['prev']) && ($truck['prev'] != null)){
			$truck['lastPicPID']--;
			if ($truck['lastPicPID'] <= 0){
				$truck['lastPicPID'] = 0;
			}
		}
		$start = $truck['lastPicPID'] * System_Properties::MAX_PHOTO_GALLERY;
		if ($start > $maxTruckPic){
			$truck['lastPicPID']--;
			if ($truck['lastPicPID'] <= 0){
				$truck['lastPicPID'] = 0;
			}
			$start = $truck['lastPicPID'] * System_Properties::MAX_PHOTO_GALLERY;
		}
		$end = $start + System_Properties::MAX_PHOTO_GALLERY;
		if($end > $maxTruckPic){
			$end = $maxTruckPic;
		}
		
		for($i = $start; $i < $end; $i++){
			if(isset($truck['truckPics'][$i])){
				$truckPic = $truck['truckPics'][$i];
				$photoGallery .= '	<li class="photo">
										<a href="/truck/pic/pid/'.$truckPic['vPicID'].'" target="_blank"><img src="/pic/'.System_Properties::TRUCK_ABRV.'_'.$truckPic['vID'].'_'.$truckPic['vPicID'].'.jpeg"/></a>
									</li>';
				//<a href="/truck/'.$truck['truckID'].'/'.$truck['page'].'/vp/'.$truckPic['vPicID'].'" target="_blank"><img src="/pic/'.$truckPic['vID'].'_'.$truckPic['vPicID'].'.jpeg"/></a>
			}else{
				break;
			}
		}
		$photoGallery .= '
				</ul>
				</div>';
		if($maxTruckPic > System_Properties::MAX_PHOTO_GALLERY){
			$photoGallery .= '
				<form action="/truck/'.$truck['truckID'].'/'.$truck['page'].'/pid/'.$truck['lastPicPID'].'" method="post">
					<input type="submit" name="prev" value="&lt;"/>
					<input type="submit" name="next" value="&gt;"/>
				</form>';
		}
	}
}
else{
	$photoGallery = '<div id="photoGalleryCont"><ul id="photoGallery">
						<li class="photo">
							<img src="'.System_Properties::NO_PIC_PATH.'"/>
						</li>
					</ul>
					</div>';
}
$tmpl -> setValue('PHOTO_GALLERY', $photoGallery);



//FORM_ACTION_PARAM
$tmpl -> setValue('FORM_ACTION_PARAM', '/'.$truck['truckID'].'/'.$truck['page']);
//TRUCK_ID
$tmpl -> setValue('TRUCK_ID', $truck['truckID']);
//SEARCH_RES_PAGE
$tmpl -> setValue('SEARCH_RES_PAGE', $truck['page']);

//USER_LINK_ADS_VAL
$userLinkAdsVal = '';
if (isset($truck['userLinkAds']) && ($truck['userLinkAds'] == 1)){
	$userLinkAdsVal = '<li><a href="/dealer/'.$truck['userID'].'">>>>> '.$lang['TXT_121'].'</a></li>';
}
$tmpl -> setValue('USER_LINK_ADS_VAL', $userLinkAdsVal);

$infoVal = '';
if (isset($this -> error)){
	$infoVal .= $this -> error;
}
if (isset($this -> info)){
	$infoVal .= $this -> info;
}
$tmpl -> setValue('INFO', $infoVal);

echo $this -> tmpl -> render();

//<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
?>