<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100825
 * Desc:		This view render the form for truck search results
 *********************************************************************************/
include_once('default/views/helpers/func_pageCounter.phtml');
include_once('default/views/filters/FormatStr2Num.php');
include_once('default/views/filters/FilterIsEmptyString.php');

$tmpl = $this -> tmpl;
$lang = $this -> lang;
$formatStr2Num = new FormatSt2Num();
$isEmptyString = new FilterIsEmptyString();

$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/truck_search.css" />'
				);	

include_once('default/views/scripts/truck/truckQS.phtml');
$tmpl -> setValue('QS_FORM_ACTION', '/truck/search');
$tmpl -> setValue('QS_HEADING', $lang['TXT_196']);
$tmpl -> readTmplFile('CONTENT', 'default/truck/search2.html');

$searchResEntryTMPL = $tmpl -> readFile('default/searchResEntry.html');

//Preparing search results and add this to the content
$truckAds = '';
if (isset($this -> truckAds) && is_array($this -> truckAds)){
	if (isset($this -> truckAds['truckAds'])){
		$truckAds = '<div class="search_res">';
		foreach ($this -> truckAds['truckAds'] AS $truckAd){
			//Determine truck pic
			$picURI = System_Properties::SYS_PIC_PATH.'/noImg.png';
			if (isset($truckAd['truckPics']) && is_array($truckAd['truckPics'])){
				foreach ($truckAd['truckPics'] AS $truckPic){
					$pic = System_Properties::PIC_PATH.'/'.System_Properties::TRUCK_ABRV.'_'.$truckAd['truckID'].'_'.$truckPic['vPicID'].'.jpeg';
					if(file_exists('.'.$pic)){
						$picURI = $pic;
						break;
					}
				}
			}
			
			//Determine truck brand
			$truckBrand = $truckAd['truckBrandName'];
			$semLink = str_ireplace('.','',str_ireplace(' ', '', $truckAd['truckBrandName'])).'-';
			
			if (isset($truckAd['truckModelName'])){
				$truckBrand .= ' '.$truckAd['truckModelName'];
				$semLink .= str_ireplace('.','',str_ireplace(' ', '', $truckAd['truckModelName'])).'-';
			}
			
			$adDetail = '';
			
			//truckPrice
			if (isset($truckAd['truckPrice'])){
				if(isset($truckAd['mwst']) && ($truckAd['mwst'] == 1)
					&& isset($truckAd['mwstSatz']) && ($truckAd['mwstSatz'] > 0)){
					$truckAd['truckPrice'] = $truckAd['truckPrice'] * ($truckAd['mwstSatz'] / 100 + 1);
				}
				$adDetail .= $formatStr2Num -> filter($truckAd['truckPrice']);
				$semLink .= $truckAd['truckPrice'];
				//truckPriceCurr
				if (isset($truckAd['truckPriceCurr']) && isset($lang['TXT_74'][$truckAd['truckPriceCurr']])){
					$adDetail .= ' '.$lang['TXT_74'][$truckAd['truckPriceCurr']];
					$semLink .= $lang['TXT_74'][$truckAd['truckPriceCurr']];
				}
				
				//truckPriceType
				if (isset($truckAd['truckPriceType']) && isset($lang['TXT_70'][$truckAd['truckPriceType']])){
					$adDetail .= ' '.$lang['TXT_70'][$truckAd['truckPriceType']];
				}
				
				$adDetail .= ', ';
				$semLink .= '-';
			}
			
			//truckKM
			if (isset($truckAd['truckKM'])){
				$adDetail .= $formatStr2Num -> filter($truckAd['truckKM']).' ';
				$semLink .= $truckAd['truckKM'];
				if (isset($lang['TXT_75'][$truckAd['truckKMType']])){
					$adDetail .= $lang['TXT_75'][$truckAd['truckKMType']];
					$semLink .= $lang['TXT_75'][$truckAd['truckKMType']];
				}
				$adDetail .= ', ';
				$semLink .= '-';
			}
			
			//Set TRUCK_EZ
			if($truckAd['truckEZY'] == 9999){
				$adDetail .= $lang['V_STATE'][0];
				$semLink .= $lang['V_STATE'][0].'-';
			}
			elseif (($truckAd['truckEZM'] > 0) && ($truckAd['truckEZY'] > 0)){
				$adDetail .= $truckAd['truckEZM'].'/'.$truckAd['truckEZY'];
				$semLink .= $truckAd['truckEZM'].$truckAd['truckEZY'].'-';
			}
			
			//truckPower
			if (isset($truckAd['truckPower'])){
				$adDetail .= ', ';
				//0 = kW
				if(isset($truckAd['truckPowerType']) && ($truckAd['truckPowerType'] == 0)){
					$adDetail .= $formatStr2Num -> filter($truckAd['truckPower']).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($truckAd['truckPower']*90/66).' '.$lang['TXT_72'][1].')';
					
					$semLink .= $truckAd['truckPower'].$lang['TXT_72'][0].'-'.round($truckAd['truckPower']*90/66).$lang['TXT_72'][1].'-';
				}
				//1 = PS
				elseif(isset($truckAd['truckPowerType']) && ($truckAd['truckPowerType'] == 1)){
					$adDetail .= $formatStr2Num -> filter($truckAd['truckPower']*66/90).' '.$lang['TXT_72'][0];
					$adDetail .= ' ('.$formatStr2Num -> filter($truckAd['truckPower']).' '.$lang['TXT_72'][1].')';
					
					$semLink .= round($truckAd['truckPower']*66/90).$lang['TXT_72'][0].'-'.$truckAd['truckPower'].$lang['TXT_72'][1].'-';
				}			
			}
			
			
			if ($adDetail != ''){
				$substr = true;
				//truck
				$adDetail .= '<br/>';
				if (isset($truckAd['userFirm']) && ($truckAd['userFirm'] != '')){
					$adDetail .= $truckAd['userFirm'];
					$substr = false;
				}/*
				elseif (isset($truckAd['userNName']) && isset($truckAd['userVName'])
					&& ($truckAd['userNName'] != '') && ($truckAd['userVName'] != '')){
					$adDetail .= $truckAd['userNName'].' '.$truckAd['userVName'];
				}*/
				
			
				
				//truckLocPLZ, truckLocOrt
				if (isset($truckAd['truckUserPLZ']) || isset($truckAd['truckLocOrt']) || isset($truckAd['truckLocCountry'])){
					$truckLoc = '';
					if ($isEmptyString -> filter($truckAd['truckLocPLZ']) == false){
						if ($truckLoc == ''){
							$truckLoc .= ', '.$lang['TXT_114'].':';
						}
						$truckLoc .= ' '.$truckAd['truckLocPLZ'];
					}
					if ($isEmptyString -> filter($truckAd['truckLocOrt']) == false){
						if ($truckLoc == ''){
							$truckLoc .= ', '.$lang['TXT_114'].':';
						}
						$truckLoc .= ' '.$truckAd['truckLocOrt'];
					}
					
					if (isset($lang['COUNTRY'][$truckAd['truckLocCountry']])){
						if ($truckLoc == ''){
							$truckLoc .= ', '.$lang['TXT_114'].':';
						}
						$truckLoc .= ' '.$lang['COUNTRY'][$truckAd['truckLocCountry']];
					}
				
					if ($truckLoc != ''){
						if ($substr == true){
							$truckLoc = substr($truckLoc,2);
						}
						$adDetail .= $truckLoc;
					}
				}elseif (isset($truckAd['userPLZ']) || isset($truckAd['userOrt'])){
					$truckLoc = '';
					if ($isEmptyString -> filter($truckAd['userPLZ']) == false){
						if ($truckLoc == ''){
							$truckLoc .= ', '.$lang['TXT_114'].':';
						}
						$truckLoc .= ' '.$truckAd['userPLZ'];
					}
					if ($isEmptyString -> filter($truckAd['userOrt']) == false){
						if ($truckLoc == ''){
							$truckLoc .= ', '.$lang['TXT_114'].':';
						}
						$truckLoc .= ' '.$truckAd['userOrt'];
					}
				
					if ($truckLoc != ''){
						if ($substr == true){
							$truckLoc = substr($truckLoc,2);
						}
						$adDetail .= $truckLoc;
					}
				}
			}
			
			$semLink = substr($semLink, 0, -1);			
			
			$searchResEntry = $tmpl -> replace(	'PIC_URI',
												$picURI,
												$searchResEntryTMPL
												);
			$searchResEntry = $tmpl -> replace(	'BRAND_URL',
												'/truck/'.$truckAd['truckID'].'/'.$this -> truckAds['actPage'].'/'.$semLink,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'BRAND_NAME',
												$truckBrand,
												$searchResEntry
												);	
			$searchResEntry = $tmpl -> replace(	'AD_DETAIL',
												$adDetail,
												$searchResEntry
												);
			$truckAds .= $searchResEntry;	
		}
		$truckAds .= '</div>';
		
		//Check if javascript is activated
		// if it is so then use javascript page counter
		// else use standard page counter
		/*
		if(isset($this -> truckAds['jsActive']) && isset($this -> truckAds['totalAds'])){//Javascript activated
			if($this -> truckAds['totalAds'] > System_Properties::NUM_ADS){
				//Prepare the search result entry template
				$gl_sret = $tmpl -> replace('PIC_URI',
											'p1',
											$searchResEntryTMPL
											);
				$gl_sret = $tmpl -> replace('BRAND_URL',
											'p2',
											$gl_sret
											);	
				$gl_sret = $tmpl -> replace('BRAND_NAME',
											'p3',
											$gl_sret
											);		
				
				//CSS Files
				$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
												.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/next_search_res.css" />'
								);
				//Set JS Code																
				$tmpl -> setValue('JS_CODE', $tmpl -> getValue('JS_CODE')
											.'
											var gl_param = new Array();
											gl_param["actSearchHits"] = '.count($this -> truckAds['truckAds']).';
											gl_param["sret"] = \''.$gl_sret.'\';
											gl_param["noPicURL"] = \''.System_Properties::SYS_PIC_PATH.'/noImg.png\';
											gl_param["picPath"] = \''.System_Properties::PIC_PATH.'\';'									
								);
				//Set JS File
				$tmpl -> setValue('JS_FILES', '	<script type="text/javascript" src="'.System_Properties::JS_PATH.'/jq_141_min.js"></script>
												<script type="text/javascript" src="'.System_Properties::JS_PATH.'/cs.js"></script>');
				
				$nextSearchResultTMPL = $tmpl -> readFile('default/nextSearchResult.html');
				$nextSearchResult = $tmpl -> replace(	'SEARCH_HITS',
														$this -> truckAds['numAds'],
														$nextSearchResultTMPL
													);		
				$truckAds .= $nextSearchResult;
			}
		}else{//Javascript deactivated
			*/
			$truckAds .= pageCounter($this -> truckAds['totalAds'], '/truck/search/', $this -> truckAds['actPage'], $this -> truckAds['numAds']);
		//}
	}
	else{
		$truckAds .= $lang['TXT_115'];
	}
}

$tmpl -> setValue('TRUCK_ADS', $truckAds);

echo $tmpl -> render();
?>
