<?php
/**********************************************************************************
 * Author: 		Fromm Alexander
 * Date: 		20100825
 * Desc:		This view render the form for truck searching
 *********************************************************************************/
include_once('default/views/filters/FilterPower.php');

$tmpl = $this -> tmpl;
$lang = $this -> lang;
$searchParam = $this -> searchParam;
$truckCat = $this -> truckCat;
$tmpl -> setValue('CSS_FILES', $tmpl -> getValue('CSS_FILES')
								.'<link rel="stylesheet" type="text/css" href="'.System_Properties::CSS_PATH.'/truck_search.css" />'
				);
$tmpl -> setValue('JS_FILES', $tmpl -> getValue('JS_FILES').'
								<script type="text/javascript" src="'.System_Properties::JS_PATH.'/ts.js"></script>');		
$tmpl -> readTmplFile('CONTENT', 'default/truck/search1.html');

//Set TRUCK_BRAND

//Set TRUCK_BRAND
$truckBrands = '';
if(isset($this -> truckBrand) && is_array($this -> truckBrand)){
	$i2 = 0;
	$truckBrands .= '	<ul class="brand">';
	foreach ($this -> truckBrand as $truckBrand){
		$truckModel = '';
		$truckBrands .= '<li '.(($i2%2) == 0 ? 'class="grey"' : '').'><input type="checkbox" name="truckBrand[]" value="'.$truckBrand['truckBrandID'].'" class="truckBrand" ';
		if (isset($searchParam['truckBrand']) && in_array($truckBrand['truckBrandID'], $searchParam['truckBrand'])){
			$truckBrands .= 'checked';
			
			//process truck model
			if (isset($this -> truckModel) && is_array($this -> truckModel)){
				$truckModel = '<ul class="model">';
				foreach ($this -> truckModel as $cm){
					if ($cm['truckBrandID'] == $truckBrand['truckBrandID']){
						$truckModel .= '<li class="l'.$cm['level'].'"><input type="checkbox" name="truckModel[]" value="'.$cm['truckModelID'].'" ';
						if (isset($searchParam['truckModel']) && in_array($cm['truckModelID'], $searchParam['truckModel'])){
							$truckModel .= 'checked';
						}						
						$truckModel .= '/>'.$cm['truckModelName'].'</li>';
					}
				}
				$truckModel .= '</ul>';
			}
		}
		$truckBrands .= '>'.$truckBrand['brandName'].$truckModel.'</li>';
		$i2++;
	}
	$truckBrands .= '</ul>';
}
$tmpl -> setValue('TRUCK_BRAND_N_MODEL', $truckBrands);


/*
$truckBrands = '';
if(isset($this -> truckBrand) && is_array($this -> truckBrand)){
	$truckBrands .= '	<ul>';
	foreach ($this -> truckBrand as $truckBrand){
		$truckModel = '';
		$truckBrands .= '<li class="truckBrand"><input type="checkbox" name="truckBrand[]" value="'.$truckBrand['truckBrandID'].'" class="truckBrand" ';
		if (isset($searchParam['truckBrand']) && in_array($truckBrand['truckBrandID'], $searchParam['truckBrand'])){
			$truckBrands .= 'checked';
			
			//process truck model
			if (isset($this -> truckModel) && is_array($this -> truckModel)){
				$truckModel = '<div class="truckModel">';
				foreach ($this -> truckModel as $cm){
					if ($cm['truckBrandID'] == $truckBrand['truckBrandID']){
						$truckModel .= '<input type="checkbox" name="truckModel[]" value="'.$cm['truckModelID'].'" ';
						if (isset($searchParam['truckModel']) && in_array($cm['truckModelID'], $searchParam['truckModel'])){
							$truckModel .= 'checked';
						}						
						$truckModel .= '/>'.$cm['truckModelName'].'<br/>';
					}
				}
				$truckModel .= '</div>';
			}
		}
		$truckBrands .= '>'.$truckBrand['brandName'].$truckModel.'</li>';
	}
	$truckBrands .= '</ul>';
}
$tmpl -> setValue('TRUCK_BRAND_N_MODEL', $truckBrands);

$truckBrands = '';
if(isset($this -> truckBrand) && is_array($this -> truckBrand)){
	$truckBrands .= '	<ul>';
	foreach ($this -> truckBrand as $truckBrand){
		$truckBrands .= '<li class="truckBrand"><input type="checkbox" name="truckBrand[]" value="'.$truckBrand['truckBrandID'].'">'.$truckBrand['brandName'].'</li>';
	}
	$truckBrands .= '</ul>';
}
$tmpl -> setValue('TRUCK_BRAND_N_MODEL', $truckBrands);
*/

//Set TRUCK_MODEL
$truckModels = '';
if(isset($this -> truckModel) && is_array($this -> truckModel)){
	$truckModels .= '	<select name="truckModel">';
	foreach ($this -> truckModel as $truckModel){
		$truckModels .= '<option value="'.$truckModel['truckModelID'].'">'.$truckModel['truckModelName'].'</option>';
	}
	$truckModels .= '	</select>';
}
$tmpl -> setValue('TRUCK_MODEL_VAL', $truckModels);

//Set TRUCK_EZ_M and CAT_EZ_Y
$truckEZF = '	<select name="truckEZF">
				<option value="-1" selected>{-TXT_8-}</option>';
for($i = date('Y'); $i > 1900; $i--){
	$truckEZF .= '<option value="'.$i.'" ';
	if (isset($searchParam['truckEZF']) && ($searchParam['truckEZF'] == $i)){
		$truckEZF .= 'selected';
	}
	$truckEZF .= '>'.$i.'</option>';
  }            
$truckEZF .= '</select>';
$tmpl -> setValue('TRUCK_EZF', $truckEZF);

$truckEZT = '<select name="truckEZT">
				<option value="-1">{-TXT_9-}</option>';
for($i = date('Y'); $i > 1900; $i--){
	$truckEZT .= '<option value="'.$i.'" ';
	if (isset($searchParam['truckEZT']) && ($searchParam['truckEZT'] == $i)){
		$truckEZT .= 'selected';
	}	
	$truckEZT .= '>'.$i.'</option>';
}            
$truckEZT .= '</select>';
$tmpl -> setValue('TRUCK_EZT', $truckEZT);

$tmpl -> setValue('TRUCK_KW', $lang['TXT_72'][0]);
$tmpl -> setValue('TRUCK_PS', $lang['TXT_72'][1]);

//TRUCK_PRICE_F
$truckPriceF = '<select name="truckPriceF">
				<option value="-1" '.(isset($searchParam['truckPriceF']) && ($searchParam['truckPriceF'] == -1)?'selected':'').'>'.$lang['TXT_8'].'</option>
		  		<option value="0" '.(isset($searchParam['truckPriceF']) && ($searchParam['truckPriceF'] == 0)?'selected':'').'>'.$lang['TXT_11'].' '.number_format($lang['TRUCK_PRICE'][0], 0, ',', '.').'</option>';
foreach ($lang['TRUCK_PRICE'] as $truckPrice){
	$truckPriceF .= '<option value="'.$truckPrice.'" ';
	if (isset($searchParam['truckPriceF']) && ($searchParam['truckPriceF'] == $truckPrice)){
		$truckPriceF .= 'selected';
	}	
	$truckPriceF .= '>'.number_format($truckPrice, 0, ',', '.').'</option>';
}
$truckPriceF .= '</select>';
$tmpl -> setValue('TRUCK_PRICE_F', $truckPriceF);
//TRUCK_PRICE_T
$truckPriceT = '<select name="truckPriceT">
				<option value="-1" '.(isset($searchParam['truckPriceT']) && ($searchParam['truckPriceT'] == -1)?'selected':'').'>'.$lang['TXT_9'].'</option>';
foreach ($lang['TRUCK_PRICE'] as $truckPrice){
	$truckPriceT .= '<option value="'.$truckPrice.'" ';
	if (isset($searchParam['truckPriceT']) && ($searchParam['truckPriceT'] == $truckPrice)){
		$truckPriceT .= 'selected';
	}	
	$truckPriceT .= '>'.number_format($truckPrice, 0, ',', '.').'</option>';
}
$truckPriceT .= '	<option value="0" '.(isset($searchParam['truckPriceT']) && ($searchParam['truckPriceT'] == 0)?'selected':'').'>'.$lang['TXT_12'].' '.number_format($truckPrice, 0, ',', '.').'</option>
		  		</select>';
$tmpl -> setValue('TRUCK_PRICE_T', $truckPriceT);
$tmpl -> setValue('TRUCK_PRICE_TYPE', $lang['TXT_128'].' '.$lang['TXT_74'][0]);

//TRUCK_POWER_F
$filterPSPower = new FilterPower(array('kind' => FilterPower::PS));
$truckPowerF = '<select name="truckPowerF">
				<option value="-1">'.$lang['TXT_8'].'</option>
	  			<option value="0">'.$lang['TXT_11'].' '.$lang['TRUCK_POWER'][0].' '.$lang['TXT_72'][0].' ('.number_format($filterPSPower->filter($lang['TRUCK_POWER'][0]), 0, ',', '.').' '.$lang['TXT_72'][1].')</option>';
foreach ($lang['TRUCK_POWER'] as $truckPower){
	$truckPowerF .= '<option value="'.$truckPower.'" ';
	if (isset($searchParam['truckPowerF']) && ($searchParam['truckPowerF'] == $truckPower)){
		$truckPowerF .= 'selected';
	}	
	$truckPowerF .= '>'.$truckPower.' '.$lang['TXT_72'][0].' ('.number_format($filterPSPower->filter($truckPower), 0, ',', '.').' '.$lang['TXT_72'][1].')</option>';
}
$truckPowerF .= '</select>';
$tmpl -> setValue('TRUCK_POWER_F', $truckPowerF);
//TRUCK_POWER_T
$truckPowerT = '<select name="truckPowerT">
				<option value="-1">'.$lang['TXT_9'].'</option>';
foreach ($lang['TRUCK_POWER'] as $truckPower){
	$truckPowerT .= '<option value="'.$truckPower.'" ';
	if (isset($searchParam['truckPowerT']) && ($searchParam['truckPowerT'] == $truckPower)){
		$truckPowerT .= 'selected';
	}	
	$truckPowerT .= '>'.$truckPower.' '.$lang['TXT_72'][0].' ('.number_format($filterPSPower->filter($truckPower), 0, ',', '.').' '.$lang['TXT_72'][1].')</option>';
}
$truckPowerT .= '<option value="0">'.$lang['TXT_12'].' '.$truckPower.' '.$lang['TXT_72'][0].' ('.number_format($filterPSPower->filter($truckPower), 0, ',', '.').' '.$lang['TXT_72'][1].')</option>
				</select>';
$tmpl -> setValue('TRUCK_POWER_T', $truckPowerT);

//Set TRUCK_KM_TYPE
$truckKMType = '<select name="truckKMType">
				<option value="-1">'.$lang['TXT_16'].'</option>';
foreach ($lang['TXT_75'] as $key => $val){
	$truckKMType .= '<option value="'.$key.'" ';
	if (isset($searchParam['truckKMType']) && ($searchParam['truckKMType'] == $key)){
		$truckKMType .= 'selected';
	}	
	$truckKMType .= '>'.$val.'</option>';
}
$truckKMType .= '</select>';
$tmpl -> setValue('TRUCK_KM_TYPE', $truckKMType);

//set TXT_75_0
$tmpl -> setValue('TXT_75_0', $lang['TXT_75'][0]);

//TRUCK_KM_F
$truckKMF = '<select name="truckKMF">
			<option value="-1">'.$lang['TXT_8'].'</option>			
		  	<option value="0">'.$lang['TXT_11'].' '.number_format($lang['TRUCK_KM'][0], 0, ',', '.').'</option>';
foreach($lang['TRUCK_KM'] as $truckKM){
	$truckKMF .= '<option value="'.$truckKM.'" ';
	if (isset($searchParam['truckKMF']) && ($searchParam['truckKMF'] == $truckKM)){
		$truckKMF .= 'selected';
	}	
	$truckKMF .= '>'.number_format($truckKM, 0, ',', '.').'</option>';
}
$truckKMF .= '</select>';
$tmpl -> setValue('TRUCK_KM_F', $truckKMF);
//TRUCK_KM_T
$truckKMT = '<select name="truckKMT">
			<option value="-1">'.$lang['TXT_9'].'</option>';
foreach($lang['TRUCK_KM'] as $truckKM){
	$truckKMT .= '<option value="'.$truckKM.'" ';
	if (isset($searchParam['truckKMT']) && ($searchParam['truckKMT'] == $truckKM)){
		$truckKMT .= 'selected';
	}	
	$truckKMT .= '>'.number_format($truckKM, 0, ',', '.').'</option>';
}
$truckKMT .= '<option value="0">'.$lang['TXT_12'].' '.number_format($truckKM, 0, ',', '.').'</option>
			</select>';
$tmpl -> setValue('TRUCK_KM_T', $truckKMT);

//Set TRUCK_SHIFT
$truckShift = '<select name="truckShift">
              	<option value="-1">{-TXT_16-}</option>';
foreach ($lang['V_SHIFT'] as $key => $val) {
	$truckShift .= '<option value="'.$key.'" ';
	if (isset($searchParam['truckShift']) && ($searchParam['truckShift'] == $key)){
		$truckShift .= 'selected';
	}	
	$truckShift .= '>'.$val.'</option>';
}
$truckShift .= '</select>';
$tmpl -> setValue('TRUCK_SHIFT_VAL', $truckShift);

//Set TRUCK_KLIMA
$truckKlima = '<select name="truckKlima">
				<option value="-1">{-TXT_16-}</option>';
foreach ($lang['V_KLIMA'] as $key => $val){
	$truckKlima .= '<option value="'.$key.'" ';
	if (isset($searchParam['truckKlima']) && ($key == $searchParam['truckKlima'])){
		$truckKlima .= 'selected';
	}
	$truckKlima .= '>'.$val.'</option>';	
}
$truckKlima .= '</select>';
$tmpl -> setValue('TRUCK_KLIMA', $truckKlima);

//Set TRUCK_CAT
$truckCatVal = '	<ul>';//<option value="-1">{-TXT_40-}</option>';
if (is_array($truckCat)){
	$i = 0;
	foreach ($truckCat as $key => $val){
		if (isset($lang['V_CAT'][$val['vcatID']])){
			if ($val['level'] == 1){
				$i++;	
				$i = $i%2;
			}
// 			$truckCatVal .= '<li '.($i == 1 ? 'class = "grey"':'').' style="padding-left:'.(($val['level'] > 1) ? ($val['level']*0.4).'em' : '0').';"><input type="checkbox" name="truckCat[]" value="'.$val['truckCatID'].'" ';
			$truckCatVal .= '<li style="padding-left:'.(($val['level'] > 1) ? ($val['level']*0.4).'em' : '0').';"><input type="checkbox" name="truckCat[]" value="'.$val['truckCatID'].'" ';
			if (isset($searchParam['truckCat']) && is_array($searchParam['truckCat']) && in_array($val['truckCatID'], $searchParam['truckCat'])){
				$truckCatVal .= 'checked';
			}	
			$truckCatVal .= '/>'.$lang['V_CAT'][$val['vcatID']].'</li>';
		}
	}
}         
$truckCatVal .= '</ul>';
$tmpl -> setValue('TRUCK_CAT_VAL', $truckCatVal);

//Set TRUCK_STATE
$truckState = '<ul>';//<option value="-1">{-TXT_40-}</option>';
foreach ($lang['V_STATE'] as $key => $val){
	$truckState .= '<li><input type="checkbox" name="truckState[]" value="'.$key.'" ';
	if (isset($searchParam['truckState']) && is_array($searchParam['truckState']) && in_array($key, $searchParam['truckState'])){
		$truckState .= 'checked';
	}	
	$truckState .= '/>'.$val.'</li>';
}
$truckState .= '</ul>';
$tmpl -> setValue('TRUCK_STATE_VAL', $truckState);

//Set TRUCK_FUEL
$truckFuel = '<ul>';//<option value="-1">{-TXT_40-}</option>
foreach ($lang['V_FUEL'] as $key => $val){
	$truckFuel .= '<li><input type="checkbox" name="truckFuel[]" value="'.$key.'" ';
	if (isset($searchParam['truckFuel']) && is_array($searchParam['truckFuel']) && in_array($key, $searchParam['truckFuel'])){
		$truckFuel .= 'checked';
	}	
	$truckFuel .= '/>'.$val.'</li>';
}
$truckFuel .= '</ul>';
$tmpl -> setValue('TRUCK_FUEL_VAL', $truckFuel);

//Set TRUCK_EMISSION_NORM
$truckEmissionNorm = '<ul>';//<option value="-1">{-TXT_40-}</option>
foreach ($lang['V_EMISSION_NORM'] as $key => $val){
	$truckEmissionNorm .= '<li><input type="checkbox" name="truckEmissionNorm[]" value="'.$key.'" ';
	if (isset($searchParam['truckEmissionNorm']) && is_array($searchParam['truckEmissionNorm']) && in_array($key, $searchParam['truckEmissionNorm'])){
		$truckEmissionNorm .= 'checked';
	}	
	$truckEmissionNorm .= '/>'.$val.'</li>';
}
$truckEmissionNorm .= '</ul>';
$tmpl -> setValue('TRUCK_EMISSION_NORM_VAL', $truckEmissionNorm);

//Set TRUCK_CLR
$truckClr = '	<ul>';//<option value="-1">{-TXT_40-}</option>
foreach ($lang['V_CLR'] as $key => $val){
	$truckClr .= '<li><input type="checkbox" name="truckClr[]" value="'.$key.'" ';
	if (isset($searchParam['truckClr']) && is_array($searchParam['truckClr']) && in_array($key, $searchParam['truckClr'])){
		$truckClr .= 'checked';
	}	
	$truckClr .= '/>'.$val.'</li>';
}
$truckClr .= '</ul>';
$tmpl -> setValue('TRUCK_CLR_VAL', $truckClr);

$truckClrMet = '{-TXT_20-}&nbsp;<input type="checkbox" name="truckClrMet" '.(isset($searchParam['truckClrMet']) && (($searchParam['truckClrMet'] == 'on') || ($searchParam['truckClrMet'] == true))? 'checked':'').'>';
$tmpl -> setValue('TRUCK_CLR_MET', $truckClrMet);

//Set TRUCK_ECOLOGIC_TAG
$truckEcologicTag = '<ul>
			          <li><input type="checkbox" name="truckEcologicTag[]" value="0" '.(isset($searchParam['truckEcologicTag']) && is_array($searchParam['truckEcologicTag']) && in_array(0, $searchParam['truckEcologicTag'])? 'checked':'').'>'.$lang['V_ECOLOGIC_TAG'][0].'</li>
			          <li><input type="checkbox" name="truckEcologicTag[]" value="1" '.(isset($searchParam['truckEcologicTag']) && is_array($searchParam['truckEcologicTag']) && in_array(1, $searchParam['truckEcologicTag'])? 'checked':'').'>'.$lang['V_ECOLOGIC_TAG'][1].'</li>
			          <li><input type="checkbox" name="truckEcologicTag[]" value="2" '.(isset($searchParam['truckEcologicTag']) && is_array($searchParam['truckEcologicTag']) && in_array(2, $searchParam['truckEcologicTag'])? 'checked':'').'>'.$lang['V_ECOLOGIC_TAG'][2].'</li>
			          <li><input type="checkbox" name="truckEcologicTag[]" value="3" '.(isset($searchParam['truckEcologicTag']) && is_array($searchParam['truckEcologicTag']) && in_array(3, $searchParam['truckEcologicTag'])? 'checked':'').'>'.$lang['V_ECOLOGIC_TAG'][3].'</li>
			        </ul>';

/*
 * <select name="truckEcologicTag">
			          <option value="-1">{-TXT_40-}</option>
			          <option value="0">'.$lang['V_ECOLOGIC_TAG'][0].'</option>
			          <option value="1">'.$lang['V_ECOLOGIC_TAG'][1].'</option>
			          <option value="2">'.$lang['V_ECOLOGIC_TAG'][2].'</option>
			          <option value="3">'.$lang['V_ECOLOGIC_TAG'][3].'</option>
			        </select>
			        */
$tmpl -> setValue('TRUCK_ECOLOGIC_TAG_VAL', $truckEcologicTag);


//Set TRUCK_EXTRA
$truckExtra = '<ul>';
$lastHeading = null;
if (is_array($this -> truckExt)){
	$i2 = 1;
	foreach ($this -> truckExt as $val){
		if (isset($lang['V_EXTRA'][$val['vextID']])){
			$truckExtra .= '<li ';
			if ($val['children'] > 0){
				$truckExtra .= ' class="extHeading" >';
				$lastHeading = $val;
				$i2 = 0;
			}else{			
				$i2++;
				if (($i2 % 5) == 0){
					$truckExtra .= ' class = "nl" ';
					$i2 = 1;
				}
				$truckExtra .= ' ><input type="checkbox" name="truckExt[]" value="'.$val['vextID'].'" ';				
				if (isset($searchParam['truckExt']) 
					&& (in_array($val['vextID'], $searchParam['truckExt']) == true)){
					$truckExtra .= 'checked';
				}
				$truckExtra .= ' />';
			}
			$truckExtra .= $lang['V_EXTRA'][$val['vextID']].'</li>';
		}
	}
}
$truckExtra 	 .= '<li class = "end" ></li></ul>';

/*
//Set TRUCK_EXTRA
$truckExtra = '<ul>';
$lastHeading = null;
if (is_array($this -> truckExt)){
	foreach ($this -> truckExt as $val){
		if (isset($lang['V_EXTRA'][$val['vextID']])){
			$truckExtra .= '<li';
			if ($val['children'] > 0){
				$truckExtra .= ' class="extHeading" >';
				$lastHeading = $val;
			}else{			
				$truckExtra .= ' ><input type="checkbox" name="truckExt[]" value="'.$val['vextID'].'" ';
				if (isset($searchParam['truckExt']) && (in_array($val['vextID'], $searchParam['truckExt']) == true)){
					$truckExtra .= 'checked';
				}
				$truckExtra .= '/>';
			}
			$truckExtra .= $lang['V_EXTRA'][$val['vextID']].'</li>';
		}
	}
}
$truckExtra 	 .= '</ul>';

if (isset($this -> truckExt)){
	$truckExtra .= '<ul>';
	$i = 1;
	foreach ($this -> truckExt as $val){
		if (isset($lang['V_EXTRA'][$val['vextID']])){
			$truckExtra .= '<li';
			if ($i % 4 == 0){
				$truckExtra .= ' class="nl"';
				$i = 1;
			}
			$i++;
			$truckExtra .= '><input type="checkbox" name="truckExt[]" value="'.$val['vextID'].'" ';
			if (isset($searchParam['truckExt']) && is_array($searchParam['truckExt']) && in_array($val['vextID'], $searchParam['truckExt'])){
				$truckExtra .= 'checked';
			}
			$truckExtra .= '/>'.$lang['V_EXTRA'][$val['vextID']].'</li>';
		}
	}
}*/
$tmpl -> setValue('TRUCK_EXTRA_VAL', $truckExtra);


//Set USER_ADS_VAL
$userAdsVal = '	<select name="userAds" id="userAds">					
				  <option value="-1" '.(isset($searchParam['userAds']) && ($searchParam['userAds'] == -1)? 'selected':'').'>'.$lang['TXT_16'].'</option>
				  <option value="1" '.(isset($searchParam['userAds']) && ($searchParam['userAds'] == 1)? 'selected':'').'>'.$lang['TXT_33'][1].'</option>
				  <option value="2" '.(isset($searchParam['userAds']) && ($searchParam['userAds'] == 2)? 'selected':'').'>'.$lang['TXT_33'][2].'</option>
				</select> ';
$tmpl -> setValue('USER_ADS_VAL', $userAdsVal);
/*
		<select name="userAds">
		  <option value="-1">{-TXT_40-}</option>
		  <option value="1">{-TXT_33-}</option>
		  <option value="2">{-TXT_34-}</option>
		</select> */

//SET TRUCK_AGE
$truckAge = '
		<select name="truckAge">
		  <option value="-1" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '-1')? 'selected':'').'>{-TXT_16-}</option>
		  <option value="1" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '1')? 'selected':'').'>1 {-TXT_30-}</option>
		  <option value="2" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '2')? 'selected':'').'>2 {-TXT_30-}</option>
		  <option value="3" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '3')? 'selected':'').'>3 {-TXT_30-}</option>
		  <option value="4" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '4')? 'selected':'').'>4 {-TXT_30-}</option>
		  <option value="5" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '5')? 'selected':'').'>5 {-TXT_30-}</option>
		  <option value="6" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '6')? 'selected':'').'>6 {-TXT_30-}</option>
		  <option value="7" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '7')? 'selected':'').'>7 {-TXT_30-}</option>
		  <option value="14" '.(isset($searchParam['truckAge']) && ($searchParam['truckAge'] == '14')? 'selected':'').'>14 {-TXT_30-}</option>
		</select>
		';
$tmpl -> setValue('TRUCK_AGE_VAL', $truckAge);


//SET TRUCK_SORT
$truckSort = '
		<select name="truckSort">
		  <option value="-1" '.(isset($searchParam['truckSort']) && ($searchParam['truckSort'] == '-1')? 'selected':'').'>{-TXT_16-}</option>
		  <option value="0" '.(isset($searchParam['truckSort']) && ($searchParam['truckSort'] == '0')? 'selected':'').'>{-TXT_13-}</option>
		  <option value="1" '.(isset($searchParam['truckSort']) && ($searchParam['truckSort'] == '1')? 'selected':'').'>{-TXT_10-}</option>
		  <option value="2" '.(isset($searchParam['truckSort']) && ($searchParam['truckSort'] == '2')? 'selected':'').'>{-TXT_14-}</option>
		  <option value="3 '.(isset($searchParam['truckSort']) && ($searchParam['truckSort'] == '3')? 'selected':'').'">{-TXT_26-}</option>
		</select><select name="truckSortOpt" disabled>
		  <option value="0" '.(isset($searchParam['truckSortOpt']) && ($searchParam['truckSortOpt'] == '0')? 'selected':'').'>{-TXT_35-}</option>
		  <option value="1" '.(isset($searchParam['truckSortOpt']) && ($searchParam['truckSortOpt'] == '1')? 'selected':'').'>{-TXT_36-}</option>
		</select>';
$tmpl -> setValue('TRUCK_SORT_VAL', $truckSort);

//SET TRUCK_PLZ
$truckPLZ = '<input type="text" name="truckPLZ" value="'.(isset($searchParam['truckPLZ'])? $searchParam['truckPLZ'] :'').'"/>
			<select name="truckCC" '.(!isset($searchParam['truckPLZ']) || (empty($searchParam['truckPLZ']))? 'disabled':'').'>
			  <option value="-1" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '-1')? 'selected':'').'>{-TXT_28-}</option>
			  <option value="10" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '10')? 'selected':'').'>10 {-TXT_75_0-}</option>
			  <option value="20" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '20')? 'selected':'').'>20 {-TXT_75_0-}</option>
			  <option value="30" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '30')? 'selected':'').'>30 {-TXT_75_0-}</option>
			  <option value="40" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '40')? 'selected':'').'>40 {-TXT_75_0-}</option>
			  <option value="50" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '50')? 'selected':'').'>50 {-TXT_75_0-}</option>
			  <option value="100" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '100')? 'selected':'').'>100 {-TXT_75_0-}</option>
			  <option value="150" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '150')? 'selected':'').'>150 {-TXT_75_0-}</option>
			  <option value="200" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '200')? 'selected':'').'>200 {-TXT_75_0-}</option>
			  <option value="250" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '250')? 'selected':'').'>250 {-TXT_75_0-}</option>
			  <option value="300" '.(isset($searchParam['truckCC']) && ($searchParam['truckCC'] == '300')? 'selected':'').'>300 {-TXT_75_0-}</option>
			</select>
		';
$tmpl -> setValue('TRUCK_PLZ_VAL', $truckPLZ);

//Set ERROR
$error = '';
if (isset($this -> error)){
	$error = $tmpl -> tagMsg(array('ERROR_MSG' => $this -> error));
	isset($error['RETURN']) ? $error = $error['RETURN'] : $error = '';
}
$tmpl -> setValue('ERROR', $error);

echo $tmpl -> render();


/*
 
		<select name="truckPriceF">
		  <option value="-1">{-TXT_8-}</option>
		  <option value="0">{-TXT_11-} 1.000 {-TXT_74-}</option>
		  <option value="1000">1.000 {-TXT_74-}</option>
		  <option value="2000">2.000 {-TXT_74-}</option>
		  <option value="3000">3.000 {-TXT_74-}</option>	
		  <option value="4000">4.000 {-TXT_74-}</option>
		  <option value="5000">5.000 {-TXT_74-}</option>
		  <option value="6000">6.000 {-TXT_74-}</option>
		  <option value="7000">7.000 {-TXT_74-}</option>
		  <option value="8000">8.000 {-TXT_74-}</option>
		  <option value="9000">9.000 {-TXT_74-}</option>
		  <option value="10000">10.000 {-TXT_74-}</option>
		  <option value="12000">12.000 {-TXT_74-}</option>
		  <option value="13000">13.000 {-TXT_74-}</option>
		  <option value="14000">14.000 {-TXT_74-}</option>
		  <option value="15000">15.000 {-TXT_74-}</option>
		  <option value="16000">16.000 {-TXT_74-}</option>
		  <option value="17000">17.000 {-TXT_74-}</option>
		  <option value="18000">18.000 {-TXT_74-}</option>
		  <option value="19000">19.000 {-TXT_74-}</option>
		  <option value="20000">20.000 {-TXT_74-}</option>
		  <option value="25000">25.000 {-TXT_74-}</option>
		  <option value="30000">30.000 {-TXT_74-}</option>
		  <option value="35000">35.000 {-TXT_74-}</option>
		  <option value="40000">40.000 {-TXT_74-}</option>
		  <option value="45000">45.000 {-TXT_74-}</option>
		  <option value="50000">50.000 {-TXT_74-}</option>
		  <option value="55000">55.000 {-TXT_74-}</option>
		  <option value="60000">60.000 {-TXT_74-}</option>
		  <option value="65000">65.000 {-TXT_74-}</option>
		  <option value="70000">70.000 {-TXT_74-}</option>
		  <option value="75000">75.000 {-TXT_74-}</option>
		  <option value="80000">80.000 {-TXT_74-}</option>
		  <option value="85000">85.000 {-TXT_74-}</option>
		  <option value="90000">90.000 {-TXT_74-}</option>
		  <option value="95000">95.000 {-TXT_74-}</option>
		  <option value="100000">100.000 {-TXT_74-}</option>
		</select><select name="truckPriceT">
		  <option value="-1">{-TXT_9-}</option>
		  <option value="1000">1.000 {-TXT_74-}</option>
		  <option value="2000">2.000 {-TXT_74-}</option>
		  <option value="3000">3.000 {-TXT_74-}</option>
		  <option value="4000">4.000 {-TXT_74-}</option>
		  <option value="5000">5.000 {-TXT_74-}</option>
		  <option value="6000">6.000 {-TXT_74-}</option>
		  <option value="7000">7.000 {-TXT_74-}</option>
		  <option value="8000">8.000 {-TXT_74-}</option>
		  <option value="9000">9.000 {-TXT_74-}</option>
		  <option value="10000">10.000 {-TXT_74-}</option>
		  <option value="12000">12.000 {-TXT_74-}</option>
		  <option value="13000">13.000 {-TXT_74-}</option>
		  <option value="14000">14.000 {-TXT_74-}</option>
		  <option value="15000">15.000 {-TXT_74-}</option>
		  <option value="16000">16.000 {-TXT_74-}</option>
		  <option value="17000">17.000 {-TXT_74-}</option>
		  <option value="18000">18.000 {-TXT_74-}</option>
		  <option value="19000">19.000 {-TXT_74-}</option>
		  <option value="20000">20.000 {-TXT_74-}</option>
		  <option value="25000">25.000 {-TXT_74-}</option>
		  <option value="30000">30.000 {-TXT_74-}</option>
		  <option value="35000">35.000 {-TXT_74-}</option>
		  <option value="40000">40.000 {-TXT_74-}</option>
		  <option value="45000">45.000 {-TXT_74-}</option>
		  <option value="50000">50.000 {-TXT_74-}</option>
		  <option value="55000">55.000 {-TXT_74-}</option>
		  <option value="60000">60.000 {-TXT_74-}</option>
		  <option value="65000">65.000 {-TXT_74-}</option>
		  <option value="70000">70.000 {-TXT_74-}</option>
		  <option value="75000">75.000 {-TXT_74-}</option>
		  <option value="80000">80.000 {-TXT_74-}</option>
		  <option value="85000">85.000 {-TXT_74-}</option>
		  <option value="90000">90.000 {-TXT_74-}</option>
		  <option value="95000">95.000 {-TXT_74-}</option>
		  <option value="100000">100.000 {-TXT_74-}</option>
		  <option value="-1">{-TXT_12-} 100.000 {-TXT_74-}</option>
		</select>
		
		
		<select name="truckPowerF">
		  <option value="-1">{-TXT_8-}</option>
		  <option value="0">{-TXT_11-} 25kW (34PS)</option>
		  <option value="25">25kW (34PS)</option>
		  <option value="35">35kW (48PS)</option>
		  <option value="44">44kW (60PS)</option>
		  <option value="55">55kW (75PS)</option>
		  <option value="66">66kW (90PS)</option>
		  <option value="74">74kW (101PS)</option>
		  <option value="85">85kW (116PS)</option>
		  <option value="96">96kW (131PS)</option>
		  <option value="110">110kW (150PS)</option>
		  <option value="147">147kW (200PS)</option>
		  <option value="184">184kW (251PS)</option>
		  <option value="222">222kW (303PS)</option>
		  <option value="260">260kW (355PS)</option>
		  <option value="295">295kW (402PS)</option>
		  <option value="333">333kW (454PS)</option>
		</select><select name="truckPowerT">
		  <option value="-1">{-TXT_9-}</option>
		  <option value="25">25kW (34PS)</option>
		  <option value="35">35kW (48PS)</option>
		  <option value="44">44kW (60PS)</option>
		  <option value="55">55kW (75PS)</option>
		  <option value="66">66kW (90PS)</option>
		  <option value="74">74kW (101PS)</option>
		  <option value="85">85kW (116PS)</option>
		  <option value="96">96kW (131PS)</option>
		  <option value="110">110kW (150PS)</option>
		  <option value="147">147kW (200PS)</option>
		  <option value="184">184kW (251PS)</option>
		  <option value="222">222kW (303PS)</option>
		  <option value="260">260kW (355PS)</option>
		  <option value="295">295kW (402PS)</option>
		  <option value="333">333kW (454PS)</option>
		  <option value="-1">{-TXT_12-} 333kW (454PS)</option>
		</select>
		
		
		<select name="truckKMF">
		  <option value="-1">{-TXT_8-}</option>
		  <option value="0">{-TXT_11-} 5.000</option>
		  <option value="5000">5.000</option>
		  <option value="10000">10.000</option>
		  <option value="15000">15.000</option>
		  <option value="20000">20.000</option>
		  <option value="25000">25.000</option>
		  <option value="30000">30.000</option>
		  <option value="35000">35.000</option>
		  <option value="40000">40.000</option>
		  <option value="45000">45.000</option>
		  <option value="50000">50.000</option>
		  <option value="55000">55.000</option>
		  <option value="60000">60.000</option>
		  <option value="65000">65.000</option>
		  <option value="70000">70.000</option>
		  <option value="75000">75.000</option>
		  <option value="80000">80.000</option>
		  <option value="85000">85.000</option>
		  <option value="90000">90.000</option>
		  <option value="95000">95.000</option>
		  <option value="100000">100.000</option>
		  <option value="110000">110.000</option>
		  <option value="120000">120.000</option>
		  <option value="130000">130.000</option>
		  <option value="140000">140.000</option>
		  <option value="150000">150.000</option>
		  <option value="160000">160.000</option>
		  <option value="170000">170.000</option>
		  <option value="180000">180.000</option>
		  <option value="190000">190.000</option>
		  <option value="200000">200.000</option>
		</select><select name="truckKMT">
		  <option value="-1">{-TXT_9-}</option>
		  <option value="5000">5.000</option>
		  <option value="10000">10.000</option>
		  <option value="15000">15.000</option>
		  <option value="20000">20.000</option>
		  <option value="25000">25.000</option>
		  <option value="30000">30.000</option>
		  <option value="35000">35.000</option>
		  <option value="40000">40.000</option>
		  <option value="45000">45.000</option>
		  <option value="50000">50.000</option>
		  <option value="55000">55.000</option>
		  <option value="60000">60.000</option>
		  <option value="65000">65.000</option>
		  <option value="70000">70.000</option>
		  <option value="75000">75.000</option>
		  <option value="80000">80.000</option>
		  <option value="85000">85.000</option>
		  <option value="90000">90.000</option>
		  <option value="95000">95.000</option>
		  <option value="100000">100.000</option>
		  <option value="110000">110.000</option>
		  <option value="120000">120.000</option>
		  <option value="130000">130.000</option>
		  <option value="140000">140.000</option>
		  <option value="150000">150.000</option>
		  <option value="160000">160.000</option>
		  <option value="170000">170.000</option>
		  <option value="180000">180.000</option>
		  <option value="190000">190.000</option>
		  <option value="200000">200.000</option>
		  <option value="-1">{-TXT_12-} 200.000</option>
		</select>
 */

?>
